// <copyright file="AccountsV1SecondaryAuthToken.cs" company="APIMatic">
// TwilioAccounts.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using TwilioAccounts.Standard.Utilities;

namespace TwilioAccounts.Standard.Models
{
    /// <summary>
    /// AccountsV1SecondaryAuthToken.
    /// </summary>
    public class AccountsV1SecondaryAuthToken
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        private string accountSid;
        private DateTime? dateCreated;
        private DateTime? dateUpdated;
        private string secondaryAuthToken;
        private string url;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "account_sid", false },
            { "date_created", false },
            { "date_updated", false },
            { "secondary_auth_token", false },
            { "url", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountsV1SecondaryAuthToken"/> class.
        /// </summary>
        public AccountsV1SecondaryAuthToken()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountsV1SecondaryAuthToken"/> class.
        /// </summary>
        /// <param name="accountSid">account_sid.</param>
        /// <param name="dateCreated">date_created.</param>
        /// <param name="dateUpdated">date_updated.</param>
        /// <param name="secondaryAuthToken">secondary_auth_token.</param>
        /// <param name="url">url.</param>
        public AccountsV1SecondaryAuthToken(
            string accountSid = null,
            DateTime? dateCreated = null,
            DateTime? dateUpdated = null,
            string secondaryAuthToken = null,
            string url = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();

            if (accountSid != null)
            {
                this.AccountSid = accountSid;
            }

            if (dateCreated != null)
            {
                this.DateCreated = dateCreated;
            }

            if (dateUpdated != null)
            {
                this.DateUpdated = dateUpdated;
            }

            if (secondaryAuthToken != null)
            {
                this.SecondaryAuthToken = secondaryAuthToken;
            }

            if (url != null)
            {
                this.Url = url;
            }
        }

        /// <summary>
        /// The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that the secondary Auth Token was created for.
        /// </summary>
        [JsonProperty("account_sid")]
        public string AccountSid
        {
            get
            {
                return this.accountSid;
            }

            set
            {
                this.shouldSerialize["account_sid"] = true;
                this.accountSid = value;
            }
        }

        /// <summary>
        /// The date and time in UTC when the resource was created specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("date_created")]
        public DateTime? DateCreated
        {
            get
            {
                return this.dateCreated;
            }

            set
            {
                this.shouldSerialize["date_created"] = true;
                this.dateCreated = value;
            }
        }

        /// <summary>
        /// The date and time in UTC when the resource was last updated specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("date_updated")]
        public DateTime? DateUpdated
        {
            get
            {
                return this.dateUpdated;
            }

            set
            {
                this.shouldSerialize["date_updated"] = true;
                this.dateUpdated = value;
            }
        }

        /// <summary>
        /// The generated secondary Auth Token that can be used to authenticate future API requests.
        /// </summary>
        [JsonProperty("secondary_auth_token")]
        public string SecondaryAuthToken
        {
            get
            {
                return this.secondaryAuthToken;
            }

            set
            {
                this.shouldSerialize["secondary_auth_token"] = true;
                this.secondaryAuthToken = value;
            }
        }

        /// <summary>
        /// The URI for this resource, relative to `https://accounts.twilio.com`
        /// </summary>
        [JsonProperty("url")]
        public string Url
        {
            get
            {
                return this.url;
            }

            set
            {
                this.shouldSerialize["url"] = true;
                this.url = value;
            }
        }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"AccountsV1SecondaryAuthToken : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetAccountSid()
        {
            this.shouldSerialize["account_sid"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetDateCreated()
        {
            this.shouldSerialize["date_created"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetDateUpdated()
        {
            this.shouldSerialize["date_updated"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetSecondaryAuthToken()
        {
            this.shouldSerialize["secondary_auth_token"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetUrl()
        {
            this.shouldSerialize["url"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeAccountSid()
        {
            return this.shouldSerialize["account_sid"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeDateCreated()
        {
            return this.shouldSerialize["date_created"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeDateUpdated()
        {
            return this.shouldSerialize["date_updated"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeSecondaryAuthToken()
        {
            return this.shouldSerialize["secondary_auth_token"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeUrl()
        {
            return this.shouldSerialize["url"];
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"AccountSid = {this.AccountSid ?? "null"}");
            toStringOutput.Add($"DateCreated = {(this.DateCreated == null ? "null" : this.DateCreated.ToString())}");
            toStringOutput.Add($"DateUpdated = {(this.DateUpdated == null ? "null" : this.DateUpdated.ToString())}");
            toStringOutput.Add($"SecondaryAuthToken = {this.SecondaryAuthToken ?? "null"}");
            toStringOutput.Add($"Url = {this.Url ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}