// <copyright file="AccessToken.cs" company="APIMatic">
// TwilioApIs.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using TwilioApIs.Standard.Utilities;

namespace TwilioApIs.Standard.Models
{
    /// <summary>
    /// AccessToken.
    /// </summary>
    public class AccessToken
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        private string sid;
        private string accountSid;
        private string serviceSid;
        private string entityIdentity;
        private string factorFriendlyName;
        private string token;
        private string url;
        private DateTime? dateCreated;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "sid", false },
            { "account_sid", false },
            { "service_sid", false },
            { "entity_identity", false },
            { "factor_friendly_name", false },
            { "token", false },
            { "url", false },
            { "date_created", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="AccessToken"/> class.
        /// </summary>
        public AccessToken()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AccessToken"/> class.
        /// </summary>
        /// <param name="sid">sid.</param>
        /// <param name="accountSid">account_sid.</param>
        /// <param name="serviceSid">service_sid.</param>
        /// <param name="entityIdentity">entity_identity.</param>
        /// <param name="factorType">factor_type.</param>
        /// <param name="factorFriendlyName">factor_friendly_name.</param>
        /// <param name="token">token.</param>
        /// <param name="url">url.</param>
        /// <param name="ttl">ttl.</param>
        /// <param name="dateCreated">date_created.</param>
        public AccessToken(
            string sid = null,
            string accountSid = null,
            string serviceSid = null,
            string entityIdentity = null,
            Models.AccessTokenEnumFactorTypes? factorType = null,
            string factorFriendlyName = null,
            string token = null,
            string url = null,
            int? ttl = 0,
            DateTime? dateCreated = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();

            if (sid != null)
            {
                this.Sid = sid;
            }

            if (accountSid != null)
            {
                this.AccountSid = accountSid;
            }

            if (serviceSid != null)
            {
                this.ServiceSid = serviceSid;
            }

            if (entityIdentity != null)
            {
                this.EntityIdentity = entityIdentity;
            }
            this.FactorType = factorType;

            if (factorFriendlyName != null)
            {
                this.FactorFriendlyName = factorFriendlyName;
            }

            if (token != null)
            {
                this.Token = token;
            }

            if (url != null)
            {
                this.Url = url;
            }
            this.Ttl = ttl;

            if (dateCreated != null)
            {
                this.DateCreated = dateCreated;
            }
        }

        /// <summary>
        /// A 34 character string that uniquely identifies this Access Token.
        /// </summary>
        [JsonProperty("sid")]
        public string Sid
        {
            get
            {
                return this.sid;
            }

            set
            {
                this.shouldSerialize["sid"] = true;
                this.sid = value;
            }
        }

        /// <summary>
        /// The unique SID identifier of the Account.
        /// </summary>
        [JsonProperty("account_sid")]
        public string AccountSid
        {
            get
            {
                return this.accountSid;
            }

            set
            {
                this.shouldSerialize["account_sid"] = true;
                this.accountSid = value;
            }
        }

        /// <summary>
        /// The unique SID identifier of the Verify Service.
        /// </summary>
        [JsonProperty("service_sid")]
        public string ServiceSid
        {
            get
            {
                return this.serviceSid;
            }

            set
            {
                this.shouldSerialize["service_sid"] = true;
                this.serviceSid = value;
            }
        }

        /// <summary>
        /// The unique external identifier for the Entity of the Service.
        /// </summary>
        [JsonProperty("entity_identity")]
        public string EntityIdentity
        {
            get
            {
                return this.entityIdentity;
            }

            set
            {
                this.shouldSerialize["entity_identity"] = true;
                this.entityIdentity = value;
            }
        }

        /// <summary>
        /// The Type of the Factor. Currently only `push` is supported.
        /// </summary>
        [JsonProperty("factor_type", NullValueHandling = NullValueHandling.Ignore)]
        public Models.AccessTokenEnumFactorTypes? FactorType { get; set; }

        /// <summary>
        /// A human readable description of this factor, up to 64 characters. For a push factor, this can be the device's name.
        /// </summary>
        [JsonProperty("factor_friendly_name")]
        public string FactorFriendlyName
        {
            get
            {
                return this.factorFriendlyName;
            }

            set
            {
                this.shouldSerialize["factor_friendly_name"] = true;
                this.factorFriendlyName = value;
            }
        }

        /// <summary>
        /// The access token generated for enrollment, this is an encrypted json web token.
        /// </summary>
        [JsonProperty("token")]
        public string Token
        {
            get
            {
                return this.token;
            }

            set
            {
                this.shouldSerialize["token"] = true;
                this.token = value;
            }
        }

        /// <summary>
        /// The URL of this resource.
        /// </summary>
        [JsonProperty("url")]
        public string Url
        {
            get
            {
                return this.url;
            }

            set
            {
                this.shouldSerialize["url"] = true;
                this.url = value;
            }
        }

        /// <summary>
        /// How long, in seconds, the access token is valid. Max: 5 minutes
        /// </summary>
        [JsonProperty("ttl", NullValueHandling = NullValueHandling.Ignore)]
        public int? Ttl { get; set; }

        /// <summary>
        /// The date that this access token was created, given in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("date_created")]
        public DateTime? DateCreated
        {
            get
            {
                return this.dateCreated;
            }

            set
            {
                this.shouldSerialize["date_created"] = true;
                this.dateCreated = value;
            }
        }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"AccessToken : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetSid()
        {
            this.shouldSerialize["sid"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetAccountSid()
        {
            this.shouldSerialize["account_sid"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetServiceSid()
        {
            this.shouldSerialize["service_sid"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetEntityIdentity()
        {
            this.shouldSerialize["entity_identity"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetFactorFriendlyName()
        {
            this.shouldSerialize["factor_friendly_name"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetToken()
        {
            this.shouldSerialize["token"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetUrl()
        {
            this.shouldSerialize["url"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetDateCreated()
        {
            this.shouldSerialize["date_created"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeSid()
        {
            return this.shouldSerialize["sid"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeAccountSid()
        {
            return this.shouldSerialize["account_sid"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeServiceSid()
        {
            return this.shouldSerialize["service_sid"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeEntityIdentity()
        {
            return this.shouldSerialize["entity_identity"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeFactorFriendlyName()
        {
            return this.shouldSerialize["factor_friendly_name"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeToken()
        {
            return this.shouldSerialize["token"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeUrl()
        {
            return this.shouldSerialize["url"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeDateCreated()
        {
            return this.shouldSerialize["date_created"];
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Sid = {this.Sid ?? "null"}");
            toStringOutput.Add($"AccountSid = {this.AccountSid ?? "null"}");
            toStringOutput.Add($"ServiceSid = {this.ServiceSid ?? "null"}");
            toStringOutput.Add($"EntityIdentity = {this.EntityIdentity ?? "null"}");
            toStringOutput.Add($"FactorType = {(this.FactorType == null ? "null" : this.FactorType.ToString())}");
            toStringOutput.Add($"FactorFriendlyName = {this.FactorFriendlyName ?? "null"}");
            toStringOutput.Add($"Token = {this.Token ?? "null"}");
            toStringOutput.Add($"Url = {this.Url ?? "null"}");
            toStringOutput.Add($"Ttl = {(this.Ttl == null ? "null" : this.Ttl.ToString())}");
            toStringOutput.Add($"DateCreated = {(this.DateCreated == null ? "null" : this.DateCreated.ToString())}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}