// <copyright file="Activity.cs" company="APIMatic">
// TwilioApIs.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using TwilioApIs.Standard.Utilities;

namespace TwilioApIs.Standard.Models
{
    /// <summary>
    /// Activity.
    /// </summary>
    public class Activity
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        private string accountSid;
        private bool? available;
        private DateTime? dateCreated;
        private DateTime? dateUpdated;
        private string friendlyName;
        private string sid;
        private string workspaceSid;
        private string url;
        private object links;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "account_sid", false },
            { "available", false },
            { "date_created", false },
            { "date_updated", false },
            { "friendly_name", false },
            { "sid", false },
            { "workspace_sid", false },
            { "url", false },
            { "links", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="Activity"/> class.
        /// </summary>
        public Activity()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Activity"/> class.
        /// </summary>
        /// <param name="accountSid">account_sid.</param>
        /// <param name="available">available.</param>
        /// <param name="dateCreated">date_created.</param>
        /// <param name="dateUpdated">date_updated.</param>
        /// <param name="friendlyName">friendly_name.</param>
        /// <param name="sid">sid.</param>
        /// <param name="workspaceSid">workspace_sid.</param>
        /// <param name="url">url.</param>
        /// <param name="links">links.</param>
        public Activity(
            string accountSid = null,
            bool? available = null,
            DateTime? dateCreated = null,
            DateTime? dateUpdated = null,
            string friendlyName = null,
            string sid = null,
            string workspaceSid = null,
            string url = null,
            object links = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();

            if (accountSid != null)
            {
                this.AccountSid = accountSid;
            }

            if (available != null)
            {
                this.Available = available;
            }

            if (dateCreated != null)
            {
                this.DateCreated = dateCreated;
            }

            if (dateUpdated != null)
            {
                this.DateUpdated = dateUpdated;
            }

            if (friendlyName != null)
            {
                this.FriendlyName = friendlyName;
            }

            if (sid != null)
            {
                this.Sid = sid;
            }

            if (workspaceSid != null)
            {
                this.WorkspaceSid = workspaceSid;
            }

            if (url != null)
            {
                this.Url = url;
            }

            if (links != null)
            {
                this.Links = links;
            }
        }

        /// <summary>
        /// The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Activity resource.
        /// </summary>
        [JsonProperty("account_sid")]
        public string AccountSid
        {
            get
            {
                return this.accountSid;
            }

            set
            {
                this.shouldSerialize["account_sid"] = true;
                this.accountSid = value;
            }
        }

        /// <summary>
        /// Whether the Worker is eligible to receive a Task when it occupies the Activity. A value of `true`, `1`, or `yes` indicates the Activity is available. All other values indicate that it is not. The value cannot be changed after the Activity is created.
        /// </summary>
        [JsonProperty("available")]
        public bool? Available
        {
            get
            {
                return this.available;
            }

            set
            {
                this.shouldSerialize["available"] = true;
                this.available = value;
            }
        }

        /// <summary>
        /// The date and time in GMT when the resource was created specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("date_created")]
        public DateTime? DateCreated
        {
            get
            {
                return this.dateCreated;
            }

            set
            {
                this.shouldSerialize["date_created"] = true;
                this.dateCreated = value;
            }
        }

        /// <summary>
        /// The date and time in GMT when the resource was last updated specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("date_updated")]
        public DateTime? DateUpdated
        {
            get
            {
                return this.dateUpdated;
            }

            set
            {
                this.shouldSerialize["date_updated"] = true;
                this.dateUpdated = value;
            }
        }

        /// <summary>
        /// The string that you assigned to describe the Activity resource.
        /// </summary>
        [JsonProperty("friendly_name")]
        public string FriendlyName
        {
            get
            {
                return this.friendlyName;
            }

            set
            {
                this.shouldSerialize["friendly_name"] = true;
                this.friendlyName = value;
            }
        }

        /// <summary>
        /// The unique string that we created to identify the Activity resource.
        /// </summary>
        [JsonProperty("sid")]
        public string Sid
        {
            get
            {
                return this.sid;
            }

            set
            {
                this.shouldSerialize["sid"] = true;
                this.sid = value;
            }
        }

        /// <summary>
        /// The SID of the Workspace that contains the Activity.
        /// </summary>
        [JsonProperty("workspace_sid")]
        public string WorkspaceSid
        {
            get
            {
                return this.workspaceSid;
            }

            set
            {
                this.shouldSerialize["workspace_sid"] = true;
                this.workspaceSid = value;
            }
        }

        /// <summary>
        /// The absolute URL of the Activity resource.
        /// </summary>
        [JsonProperty("url")]
        public string Url
        {
            get
            {
                return this.url;
            }

            set
            {
                this.shouldSerialize["url"] = true;
                this.url = value;
            }
        }

        /// <summary>
        /// Gets or sets Links.
        /// </summary>
        [JsonProperty("links")]
        public object Links
        {
            get
            {
                return this.links;
            }

            set
            {
                this.shouldSerialize["links"] = true;
                this.links = value;
            }
        }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"Activity : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetAccountSid()
        {
            this.shouldSerialize["account_sid"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetAvailable()
        {
            this.shouldSerialize["available"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetDateCreated()
        {
            this.shouldSerialize["date_created"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetDateUpdated()
        {
            this.shouldSerialize["date_updated"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetFriendlyName()
        {
            this.shouldSerialize["friendly_name"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetSid()
        {
            this.shouldSerialize["sid"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetWorkspaceSid()
        {
            this.shouldSerialize["workspace_sid"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetUrl()
        {
            this.shouldSerialize["url"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetLinks()
        {
            this.shouldSerialize["links"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeAccountSid()
        {
            return this.shouldSerialize["account_sid"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeAvailable()
        {
            return this.shouldSerialize["available"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeDateCreated()
        {
            return this.shouldSerialize["date_created"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeDateUpdated()
        {
            return this.shouldSerialize["date_updated"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeFriendlyName()
        {
            return this.shouldSerialize["friendly_name"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeSid()
        {
            return this.shouldSerialize["sid"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeWorkspaceSid()
        {
            return this.shouldSerialize["workspace_sid"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeUrl()
        {
            return this.shouldSerialize["url"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeLinks()
        {
            return this.shouldSerialize["links"];
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"AccountSid = {this.AccountSid ?? "null"}");
            toStringOutput.Add($"Available = {(this.Available == null ? "null" : this.Available.ToString())}");
            toStringOutput.Add($"DateCreated = {(this.DateCreated == null ? "null" : this.DateCreated.ToString())}");
            toStringOutput.Add($"DateUpdated = {(this.DateUpdated == null ? "null" : this.DateUpdated.ToString())}");
            toStringOutput.Add($"FriendlyName = {this.FriendlyName ?? "null"}");
            toStringOutput.Add($"Sid = {this.Sid ?? "null"}");
            toStringOutput.Add($"WorkspaceSid = {this.WorkspaceSid ?? "null"}");
            toStringOutput.Add($"Url = {this.Url ?? "null"}");
            toStringOutput.Add($"Links = {(this.Links == null ? "null" : this.Links.ToString())}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}