// <copyright file="Bucket.cs" company="APIMatic">
// TwilioApIs.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using TwilioApIs.Standard.Utilities;

namespace TwilioApIs.Standard.Models
{
    /// <summary>
    /// Bucket.
    /// </summary>
    public class Bucket
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        private string sid;
        private string rateLimitSid;
        private string serviceSid;
        private string accountSid;
        private DateTime? dateCreated;
        private DateTime? dateUpdated;
        private string url;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "sid", false },
            { "rate_limit_sid", false },
            { "service_sid", false },
            { "account_sid", false },
            { "date_created", false },
            { "date_updated", false },
            { "url", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="Bucket"/> class.
        /// </summary>
        public Bucket()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Bucket"/> class.
        /// </summary>
        /// <param name="sid">sid.</param>
        /// <param name="rateLimitSid">rate_limit_sid.</param>
        /// <param name="serviceSid">service_sid.</param>
        /// <param name="accountSid">account_sid.</param>
        /// <param name="max">max.</param>
        /// <param name="interval">interval.</param>
        /// <param name="dateCreated">date_created.</param>
        /// <param name="dateUpdated">date_updated.</param>
        /// <param name="url">url.</param>
        public Bucket(
            string sid = null,
            string rateLimitSid = null,
            string serviceSid = null,
            string accountSid = null,
            int? max = 0,
            int? interval = 0,
            DateTime? dateCreated = null,
            DateTime? dateUpdated = null,
            string url = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();

            if (sid != null)
            {
                this.Sid = sid;
            }

            if (rateLimitSid != null)
            {
                this.RateLimitSid = rateLimitSid;
            }

            if (serviceSid != null)
            {
                this.ServiceSid = serviceSid;
            }

            if (accountSid != null)
            {
                this.AccountSid = accountSid;
            }
            this.Max = max;
            this.Interval = interval;

            if (dateCreated != null)
            {
                this.DateCreated = dateCreated;
            }

            if (dateUpdated != null)
            {
                this.DateUpdated = dateUpdated;
            }

            if (url != null)
            {
                this.Url = url;
            }
        }

        /// <summary>
        /// A 34 character string that uniquely identifies this Bucket.
        /// </summary>
        [JsonProperty("sid")]
        public string Sid
        {
            get
            {
                return this.sid;
            }

            set
            {
                this.shouldSerialize["sid"] = true;
                this.sid = value;
            }
        }

        /// <summary>
        /// The Twilio-provided string that uniquely identifies the Rate Limit resource.
        /// </summary>
        [JsonProperty("rate_limit_sid")]
        public string RateLimitSid
        {
            get
            {
                return this.rateLimitSid;
            }

            set
            {
                this.shouldSerialize["rate_limit_sid"] = true;
                this.rateLimitSid = value;
            }
        }

        /// <summary>
        /// The SID of the [Service](https://www.twilio.com/docs/verify/api/service) the resource is associated with.
        /// </summary>
        [JsonProperty("service_sid")]
        public string ServiceSid
        {
            get
            {
                return this.serviceSid;
            }

            set
            {
                this.shouldSerialize["service_sid"] = true;
                this.serviceSid = value;
            }
        }

        /// <summary>
        /// The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Rate Limit resource.
        /// </summary>
        [JsonProperty("account_sid")]
        public string AccountSid
        {
            get
            {
                return this.accountSid;
            }

            set
            {
                this.shouldSerialize["account_sid"] = true;
                this.accountSid = value;
            }
        }

        /// <summary>
        /// Maximum number of requests permitted in during the interval.
        /// </summary>
        [JsonProperty("max", NullValueHandling = NullValueHandling.Ignore)]
        public int? Max { get; set; }

        /// <summary>
        /// Number of seconds that the rate limit will be enforced over.
        /// </summary>
        [JsonProperty("interval", NullValueHandling = NullValueHandling.Ignore)]
        public int? Interval { get; set; }

        /// <summary>
        /// The date and time in GMT when the resource was created specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("date_created")]
        public DateTime? DateCreated
        {
            get
            {
                return this.dateCreated;
            }

            set
            {
                this.shouldSerialize["date_created"] = true;
                this.dateCreated = value;
            }
        }

        /// <summary>
        /// The date and time in GMT when the resource was last updated specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("date_updated")]
        public DateTime? DateUpdated
        {
            get
            {
                return this.dateUpdated;
            }

            set
            {
                this.shouldSerialize["date_updated"] = true;
                this.dateUpdated = value;
            }
        }

        /// <summary>
        /// The URL of this resource.
        /// </summary>
        [JsonProperty("url")]
        public string Url
        {
            get
            {
                return this.url;
            }

            set
            {
                this.shouldSerialize["url"] = true;
                this.url = value;
            }
        }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"Bucket : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetSid()
        {
            this.shouldSerialize["sid"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetRateLimitSid()
        {
            this.shouldSerialize["rate_limit_sid"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetServiceSid()
        {
            this.shouldSerialize["service_sid"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetAccountSid()
        {
            this.shouldSerialize["account_sid"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetDateCreated()
        {
            this.shouldSerialize["date_created"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetDateUpdated()
        {
            this.shouldSerialize["date_updated"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetUrl()
        {
            this.shouldSerialize["url"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeSid()
        {
            return this.shouldSerialize["sid"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeRateLimitSid()
        {
            return this.shouldSerialize["rate_limit_sid"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeServiceSid()
        {
            return this.shouldSerialize["service_sid"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeAccountSid()
        {
            return this.shouldSerialize["account_sid"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeDateCreated()
        {
            return this.shouldSerialize["date_created"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeDateUpdated()
        {
            return this.shouldSerialize["date_updated"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeUrl()
        {
            return this.shouldSerialize["url"];
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Sid = {this.Sid ?? "null"}");
            toStringOutput.Add($"RateLimitSid = {this.RateLimitSid ?? "null"}");
            toStringOutput.Add($"ServiceSid = {this.ServiceSid ?? "null"}");
            toStringOutput.Add($"AccountSid = {this.AccountSid ?? "null"}");
            toStringOutput.Add($"Max = {(this.Max == null ? "null" : this.Max.ToString())}");
            toStringOutput.Add($"Interval = {(this.Interval == null ? "null" : this.Interval.ToString())}");
            toStringOutput.Add($"DateCreated = {(this.DateCreated == null ? "null" : this.DateCreated.ToString())}");
            toStringOutput.Add($"DateUpdated = {(this.DateUpdated == null ? "null" : this.DateUpdated.ToString())}");
            toStringOutput.Add($"Url = {this.Url ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}