// <copyright file="ConfigurationWebhookTarget.cs" company="APIMatic">
// TwilioApIs.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace TwilioApIs.Standard.Models
{
    /// <summary>
    /// ConfigurationWebhookTarget.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum ConfigurationWebhookTarget
    {
        /// <summary>
        /// Webhook.
        /// </summary>
        [EnumMember(Value = "webhook")]
        Webhook,

        /// <summary>
        /// Flex.
        /// </summary>
        [EnumMember(Value = "flex")]
        Flex
    }
}