// <copyright file="ConversationScopedWebhookMethod.cs" company="APIMatic">
// TwilioApIs.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace TwilioApIs.Standard.Models
{
    /// <summary>
    /// ConversationScopedWebhookMethod.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum ConversationScopedWebhookMethod
    {
        /// <summary>
        /// Get.
        /// </summary>
        [EnumMember(Value = "get")]
        Get,

        /// <summary>
        /// Post.
        /// </summary>
        [EnumMember(Value = "post")]
        Post
    }
}