// <copyright file="CredentialPushType.cs" company="APIMatic">
// TwilioApIs.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace TwilioApIs.Standard.Models
{
    /// <summary>
    /// CredentialPushType.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum CredentialPushType
    {
        /// <summary>
        /// Apn.
        /// </summary>
        [EnumMember(Value = "apn")]
        Apn,

        /// <summary>
        /// Gcm.
        /// </summary>
        [EnumMember(Value = "gcm")]
        Gcm,

        /// <summary>
        /// Fcm.
        /// </summary>
        [EnumMember(Value = "fcm")]
        Fcm
    }
}