// <copyright file="FactorEnumFactorType.cs" company="APIMatic">
// TwilioApIs.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace TwilioApIs.Standard.Models
{
    /// <summary>
    /// FactorEnumFactorType.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum FactorEnumFactorType
    {
        /// <summary>
        /// Push.
        /// </summary>
        [EnumMember(Value = "push")]
        Push,

        /// <summary>
        /// Totp.
        /// </summary>
        [EnumMember(Value = "totp")]
        Totp,

        /// <summary>
        /// Passkeys.
        /// </summary>
        [EnumMember(Value = "passkeys")]
        Passkeys
    }
}