// <copyright file="MessageEnumDirection.cs" company="APIMatic">
// TwilioApIs.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace TwilioApIs.Standard.Models
{
    /// <summary>
    /// MessageEnumDirection.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum MessageEnumDirection
    {
        /// <summary>
        /// Inbound.
        /// </summary>
        [EnumMember(Value = "inbound")]
        Inbound,

        /// <summary>
        /// Outboundapi.
        /// </summary>
        [EnumMember(Value = "outbound-api")]
        Outboundapi,

        /// <summary>
        /// Outboundcall.
        /// </summary>
        [EnumMember(Value = "outbound-call")]
        Outboundcall,

        /// <summary>
        /// Outboundreply.
        /// </summary>
        [EnumMember(Value = "outbound-reply")]
        Outboundreply
    }
}