// <copyright file="NewFactorEnumNotificationPlatforms.cs" company="APIMatic">
// TwilioApIs.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace TwilioApIs.Standard.Models
{
    /// <summary>
    /// NewFactorEnumNotificationPlatforms.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum NewFactorEnumNotificationPlatforms
    {
        /// <summary>
        /// Apn.
        /// </summary>
        [EnumMember(Value = "apn")]
        Apn,

        /// <summary>
        /// Fcm.
        /// </summary>
        [EnumMember(Value = "fcm")]
        Fcm,

        /// <summary>
        /// None.
        /// </summary>
        [EnumMember(Value = "none")]
        None
    }
}