// <copyright file="ServiceConversationMessageReceipt.cs" company="APIMatic">
// TwilioApIs.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using TwilioApIs.Standard.Utilities;

namespace TwilioApIs.Standard.Models
{
    /// <summary>
    /// ServiceConversationMessageReceipt.
    /// </summary>
    public class ServiceConversationMessageReceipt
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        private string accountSid;
        private string chatServiceSid;
        private string conversationSid;
        private string messageSid;
        private string sid;
        private string channelMessageSid;
        private string participantSid;
        private DateTime? dateCreated;
        private DateTime? dateUpdated;
        private string url;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "account_sid", false },
            { "chat_service_sid", false },
            { "conversation_sid", false },
            { "message_sid", false },
            { "sid", false },
            { "channel_message_sid", false },
            { "participant_sid", false },
            { "date_created", false },
            { "date_updated", false },
            { "url", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="ServiceConversationMessageReceipt"/> class.
        /// </summary>
        public ServiceConversationMessageReceipt()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ServiceConversationMessageReceipt"/> class.
        /// </summary>
        /// <param name="accountSid">account_sid.</param>
        /// <param name="chatServiceSid">chat_service_sid.</param>
        /// <param name="conversationSid">conversation_sid.</param>
        /// <param name="messageSid">message_sid.</param>
        /// <param name="sid">sid.</param>
        /// <param name="channelMessageSid">channel_message_sid.</param>
        /// <param name="participantSid">participant_sid.</param>
        /// <param name="status">status.</param>
        /// <param name="errorCode">error_code.</param>
        /// <param name="dateCreated">date_created.</param>
        /// <param name="dateUpdated">date_updated.</param>
        /// <param name="url">url.</param>
        public ServiceConversationMessageReceipt(
            string accountSid = null,
            string chatServiceSid = null,
            string conversationSid = null,
            string messageSid = null,
            string sid = null,
            string channelMessageSid = null,
            string participantSid = null,
            Models.ServiceConversationMessageReceiptDeliveryStatus? status = null,
            int? errorCode = 0,
            DateTime? dateCreated = null,
            DateTime? dateUpdated = null,
            string url = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();

            if (accountSid != null)
            {
                this.AccountSid = accountSid;
            }

            if (chatServiceSid != null)
            {
                this.ChatServiceSid = chatServiceSid;
            }

            if (conversationSid != null)
            {
                this.ConversationSid = conversationSid;
            }

            if (messageSid != null)
            {
                this.MessageSid = messageSid;
            }

            if (sid != null)
            {
                this.Sid = sid;
            }

            if (channelMessageSid != null)
            {
                this.ChannelMessageSid = channelMessageSid;
            }

            if (participantSid != null)
            {
                this.ParticipantSid = participantSid;
            }
            this.Status = status;
            this.ErrorCode = errorCode;

            if (dateCreated != null)
            {
                this.DateCreated = dateCreated;
            }

            if (dateUpdated != null)
            {
                this.DateUpdated = dateUpdated;
            }

            if (url != null)
            {
                this.Url = url;
            }
        }

        /// <summary>
        /// The unique ID of the [Account](https://www.twilio.com/docs/iam/api/account) responsible for this participant.
        /// </summary>
        [JsonProperty("account_sid")]
        public string AccountSid
        {
            get
            {
                return this.accountSid;
            }

            set
            {
                this.shouldSerialize["account_sid"] = true;
                this.accountSid = value;
            }
        }

        /// <summary>
        /// The SID of the [Conversation Service](https://www.twilio.com/docs/conversations/api/service-resource) the Message resource is associated with.
        /// </summary>
        [JsonProperty("chat_service_sid")]
        public string ChatServiceSid
        {
            get
            {
                return this.chatServiceSid;
            }

            set
            {
                this.shouldSerialize["chat_service_sid"] = true;
                this.chatServiceSid = value;
            }
        }

        /// <summary>
        /// The unique ID of the [Conversation](https://www.twilio.com/docs/conversations/api/conversation-resource) for this message.
        /// </summary>
        [JsonProperty("conversation_sid")]
        public string ConversationSid
        {
            get
            {
                return this.conversationSid;
            }

            set
            {
                this.shouldSerialize["conversation_sid"] = true;
                this.conversationSid = value;
            }
        }

        /// <summary>
        /// The SID of the message within a [Conversation](https://www.twilio.com/docs/conversations/api/conversation-resource) the delivery receipt belongs to
        /// </summary>
        [JsonProperty("message_sid")]
        public string MessageSid
        {
            get
            {
                return this.messageSid;
            }

            set
            {
                this.shouldSerialize["message_sid"] = true;
                this.messageSid = value;
            }
        }

        /// <summary>
        /// A 34 character string that uniquely identifies this resource.
        /// </summary>
        [JsonProperty("sid")]
        public string Sid
        {
            get
            {
                return this.sid;
            }

            set
            {
                this.shouldSerialize["sid"] = true;
                this.sid = value;
            }
        }

        /// <summary>
        /// A messaging channel-specific identifier for the message delivered to participant e.g. `SMxx` for SMS, `WAxx` for Whatsapp etc.
        /// </summary>
        [JsonProperty("channel_message_sid")]
        public string ChannelMessageSid
        {
            get
            {
                return this.channelMessageSid;
            }

            set
            {
                this.shouldSerialize["channel_message_sid"] = true;
                this.channelMessageSid = value;
            }
        }

        /// <summary>
        /// The unique ID of the participant the delivery receipt belongs to.
        /// </summary>
        [JsonProperty("participant_sid")]
        public string ParticipantSid
        {
            get
            {
                return this.participantSid;
            }

            set
            {
                this.shouldSerialize["participant_sid"] = true;
                this.participantSid = value;
            }
        }

        /// <summary>
        /// The message delivery status, can be `read`, `failed`, `delivered`, `undelivered`, `sent` or null.
        /// </summary>
        [JsonProperty("status", NullValueHandling = NullValueHandling.Ignore)]
        public Models.ServiceConversationMessageReceiptDeliveryStatus? Status { get; set; }

        /// <summary>
        /// The message [delivery error code](https://www.twilio.com/docs/sms/api/message-resource#delivery-related-errors) for a `failed` status,
        /// </summary>
        [JsonProperty("error_code", NullValueHandling = NullValueHandling.Ignore)]
        public int? ErrorCode { get; set; }

        /// <summary>
        /// The date that this resource was created.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("date_created")]
        public DateTime? DateCreated
        {
            get
            {
                return this.dateCreated;
            }

            set
            {
                this.shouldSerialize["date_created"] = true;
                this.dateCreated = value;
            }
        }

        /// <summary>
        /// The date that this resource was last updated. `null` if the delivery receipt has not been updated.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("date_updated")]
        public DateTime? DateUpdated
        {
            get
            {
                return this.dateUpdated;
            }

            set
            {
                this.shouldSerialize["date_updated"] = true;
                this.dateUpdated = value;
            }
        }

        /// <summary>
        /// An absolute API resource URL for this delivery receipt.
        /// </summary>
        [JsonProperty("url")]
        public string Url
        {
            get
            {
                return this.url;
            }

            set
            {
                this.shouldSerialize["url"] = true;
                this.url = value;
            }
        }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ServiceConversationMessageReceipt : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetAccountSid()
        {
            this.shouldSerialize["account_sid"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetChatServiceSid()
        {
            this.shouldSerialize["chat_service_sid"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetConversationSid()
        {
            this.shouldSerialize["conversation_sid"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetMessageSid()
        {
            this.shouldSerialize["message_sid"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetSid()
        {
            this.shouldSerialize["sid"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetChannelMessageSid()
        {
            this.shouldSerialize["channel_message_sid"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetParticipantSid()
        {
            this.shouldSerialize["participant_sid"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetDateCreated()
        {
            this.shouldSerialize["date_created"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetDateUpdated()
        {
            this.shouldSerialize["date_updated"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetUrl()
        {
            this.shouldSerialize["url"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeAccountSid()
        {
            return this.shouldSerialize["account_sid"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeChatServiceSid()
        {
            return this.shouldSerialize["chat_service_sid"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeConversationSid()
        {
            return this.shouldSerialize["conversation_sid"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeMessageSid()
        {
            return this.shouldSerialize["message_sid"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeSid()
        {
            return this.shouldSerialize["sid"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeChannelMessageSid()
        {
            return this.shouldSerialize["channel_message_sid"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeParticipantSid()
        {
            return this.shouldSerialize["participant_sid"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeDateCreated()
        {
            return this.shouldSerialize["date_created"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeDateUpdated()
        {
            return this.shouldSerialize["date_updated"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeUrl()
        {
            return this.shouldSerialize["url"];
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"AccountSid = {this.AccountSid ?? "null"}");
            toStringOutput.Add($"ChatServiceSid = {this.ChatServiceSid ?? "null"}");
            toStringOutput.Add($"ConversationSid = {this.ConversationSid ?? "null"}");
            toStringOutput.Add($"MessageSid = {this.MessageSid ?? "null"}");
            toStringOutput.Add($"Sid = {this.Sid ?? "null"}");
            toStringOutput.Add($"ChannelMessageSid = {this.ChannelMessageSid ?? "null"}");
            toStringOutput.Add($"ParticipantSid = {this.ParticipantSid ?? "null"}");
            toStringOutput.Add($"Status = {(this.Status == null ? "null" : this.Status.ToString())}");
            toStringOutput.Add($"ErrorCode = {(this.ErrorCode == null ? "null" : this.ErrorCode.ToString())}");
            toStringOutput.Add($"DateCreated = {(this.DateCreated == null ? "null" : this.DateCreated.ToString())}");
            toStringOutput.Add($"DateUpdated = {(this.DateUpdated == null ? "null" : this.DateUpdated.ToString())}");
            toStringOutput.Add($"Url = {this.Url ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}