// <copyright file="ServiceConversationScopedWebhook.cs" company="APIMatic">
// TwilioApIs.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using TwilioApIs.Standard.Utilities;

namespace TwilioApIs.Standard.Models
{
    /// <summary>
    /// ServiceConversationScopedWebhook.
    /// </summary>
    public class ServiceConversationScopedWebhook
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        private string sid;
        private string accountSid;
        private string chatServiceSid;
        private string conversationSid;
        private string target;
        private string url;
        private object configuration;
        private DateTime? dateCreated;
        private DateTime? dateUpdated;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "sid", false },
            { "account_sid", false },
            { "chat_service_sid", false },
            { "conversation_sid", false },
            { "target", false },
            { "url", false },
            { "configuration", false },
            { "date_created", false },
            { "date_updated", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="ServiceConversationScopedWebhook"/> class.
        /// </summary>
        public ServiceConversationScopedWebhook()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ServiceConversationScopedWebhook"/> class.
        /// </summary>
        /// <param name="sid">sid.</param>
        /// <param name="accountSid">account_sid.</param>
        /// <param name="chatServiceSid">chat_service_sid.</param>
        /// <param name="conversationSid">conversation_sid.</param>
        /// <param name="target">target.</param>
        /// <param name="url">url.</param>
        /// <param name="configuration">configuration.</param>
        /// <param name="dateCreated">date_created.</param>
        /// <param name="dateUpdated">date_updated.</param>
        public ServiceConversationScopedWebhook(
            string sid = null,
            string accountSid = null,
            string chatServiceSid = null,
            string conversationSid = null,
            string target = null,
            string url = null,
            object configuration = null,
            DateTime? dateCreated = null,
            DateTime? dateUpdated = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();

            if (sid != null)
            {
                this.Sid = sid;
            }

            if (accountSid != null)
            {
                this.AccountSid = accountSid;
            }

            if (chatServiceSid != null)
            {
                this.ChatServiceSid = chatServiceSid;
            }

            if (conversationSid != null)
            {
                this.ConversationSid = conversationSid;
            }

            if (target != null)
            {
                this.Target = target;
            }

            if (url != null)
            {
                this.Url = url;
            }

            if (configuration != null)
            {
                this.Configuration = configuration;
            }

            if (dateCreated != null)
            {
                this.DateCreated = dateCreated;
            }

            if (dateUpdated != null)
            {
                this.DateUpdated = dateUpdated;
            }
        }

        /// <summary>
        /// A 34 character string that uniquely identifies this resource.
        /// </summary>
        [JsonProperty("sid")]
        public string Sid
        {
            get
            {
                return this.sid;
            }

            set
            {
                this.shouldSerialize["sid"] = true;
                this.sid = value;
            }
        }

        /// <summary>
        /// The unique ID of the [Account](https://www.twilio.com/docs/iam/api/account) responsible for this conversation.
        /// </summary>
        [JsonProperty("account_sid")]
        public string AccountSid
        {
            get
            {
                return this.accountSid;
            }

            set
            {
                this.shouldSerialize["account_sid"] = true;
                this.accountSid = value;
            }
        }

        /// <summary>
        /// The SID of the [Conversation Service](https://www.twilio.com/docs/conversations/api/service-resource) the Participant resource is associated with.
        /// </summary>
        [JsonProperty("chat_service_sid")]
        public string ChatServiceSid
        {
            get
            {
                return this.chatServiceSid;
            }

            set
            {
                this.shouldSerialize["chat_service_sid"] = true;
                this.chatServiceSid = value;
            }
        }

        /// <summary>
        /// The unique ID of the [Conversation](https://www.twilio.com/docs/conversations/api/conversation-resource) for this webhook.
        /// </summary>
        [JsonProperty("conversation_sid")]
        public string ConversationSid
        {
            get
            {
                return this.conversationSid;
            }

            set
            {
                this.shouldSerialize["conversation_sid"] = true;
                this.conversationSid = value;
            }
        }

        /// <summary>
        /// The target of this webhook: `webhook`, `studio`, `trigger`
        /// </summary>
        [JsonProperty("target")]
        public string Target
        {
            get
            {
                return this.target;
            }

            set
            {
                this.shouldSerialize["target"] = true;
                this.target = value;
            }
        }

        /// <summary>
        /// An absolute API resource URL for this webhook.
        /// </summary>
        [JsonProperty("url")]
        public string Url
        {
            get
            {
                return this.url;
            }

            set
            {
                this.shouldSerialize["url"] = true;
                this.url = value;
            }
        }

        /// <summary>
        /// The configuration of this webhook. Is defined based on target.
        /// </summary>
        [JsonProperty("configuration")]
        public object Configuration
        {
            get
            {
                return this.configuration;
            }

            set
            {
                this.shouldSerialize["configuration"] = true;
                this.configuration = value;
            }
        }

        /// <summary>
        /// The date that this resource was created.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("date_created")]
        public DateTime? DateCreated
        {
            get
            {
                return this.dateCreated;
            }

            set
            {
                this.shouldSerialize["date_created"] = true;
                this.dateCreated = value;
            }
        }

        /// <summary>
        /// The date that this resource was last updated.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("date_updated")]
        public DateTime? DateUpdated
        {
            get
            {
                return this.dateUpdated;
            }

            set
            {
                this.shouldSerialize["date_updated"] = true;
                this.dateUpdated = value;
            }
        }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ServiceConversationScopedWebhook : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetSid()
        {
            this.shouldSerialize["sid"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetAccountSid()
        {
            this.shouldSerialize["account_sid"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetChatServiceSid()
        {
            this.shouldSerialize["chat_service_sid"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetConversationSid()
        {
            this.shouldSerialize["conversation_sid"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetTarget()
        {
            this.shouldSerialize["target"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetUrl()
        {
            this.shouldSerialize["url"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetConfiguration()
        {
            this.shouldSerialize["configuration"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetDateCreated()
        {
            this.shouldSerialize["date_created"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetDateUpdated()
        {
            this.shouldSerialize["date_updated"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeSid()
        {
            return this.shouldSerialize["sid"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeAccountSid()
        {
            return this.shouldSerialize["account_sid"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeChatServiceSid()
        {
            return this.shouldSerialize["chat_service_sid"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeConversationSid()
        {
            return this.shouldSerialize["conversation_sid"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeTarget()
        {
            return this.shouldSerialize["target"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeUrl()
        {
            return this.shouldSerialize["url"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeConfiguration()
        {
            return this.shouldSerialize["configuration"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeDateCreated()
        {
            return this.shouldSerialize["date_created"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeDateUpdated()
        {
            return this.shouldSerialize["date_updated"];
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Sid = {this.Sid ?? "null"}");
            toStringOutput.Add($"AccountSid = {this.AccountSid ?? "null"}");
            toStringOutput.Add($"ChatServiceSid = {this.ChatServiceSid ?? "null"}");
            toStringOutput.Add($"ConversationSid = {this.ConversationSid ?? "null"}");
            toStringOutput.Add($"Target = {this.Target ?? "null"}");
            toStringOutput.Add($"Url = {this.Url ?? "null"}");
            toStringOutput.Add($"Configuration = {(this.Configuration == null ? "null" : this.Configuration.ToString())}");
            toStringOutput.Add($"DateCreated = {(this.DateCreated == null ? "null" : this.DateCreated.ToString())}");
            toStringOutput.Add($"DateUpdated = {(this.DateUpdated == null ? "null" : this.DateUpdated.ToString())}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}