// <copyright file="ServiceUserConversationNotificationLevel.cs" company="APIMatic">
// TwilioApIs.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace TwilioApIs.Standard.Models
{
    /// <summary>
    /// ServiceUserConversationNotificationLevel.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum ServiceUserConversationNotificationLevel
    {
        /// <summary>
        /// Default.
        /// </summary>
        [EnumMember(Value = "default")]
        Default,

        /// <summary>
        /// Muted.
        /// </summary>
        [EnumMember(Value = "muted")]
        Muted
    }
}