// <copyright file="ServiceConversationParticipant.cs" company="APIMatic">
// TwilioApIs.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using TwilioApIs.Standard.Utilities;

namespace TwilioApIs.Standard.Models
{
    /// <summary>
    /// ServiceConversationParticipant.
    /// </summary>
    public class ServiceConversationParticipant
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        private string accountSid;
        private string chatServiceSid;
        private string conversationSid;
        private string sid;
        private string identity;
        private string attributes;
        private object messagingBinding;
        private string roleSid;
        private DateTime? dateCreated;
        private DateTime? dateUpdated;
        private string url;
        private int? lastReadMessageIndex;
        private string lastReadTimestamp;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "account_sid", false },
            { "chat_service_sid", false },
            { "conversation_sid", false },
            { "sid", false },
            { "identity", false },
            { "attributes", false },
            { "messaging_binding", false },
            { "role_sid", false },
            { "date_created", false },
            { "date_updated", false },
            { "url", false },
            { "last_read_message_index", false },
            { "last_read_timestamp", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="ServiceConversationParticipant"/> class.
        /// </summary>
        public ServiceConversationParticipant()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ServiceConversationParticipant"/> class.
        /// </summary>
        /// <param name="accountSid">account_sid.</param>
        /// <param name="chatServiceSid">chat_service_sid.</param>
        /// <param name="conversationSid">conversation_sid.</param>
        /// <param name="sid">sid.</param>
        /// <param name="identity">identity.</param>
        /// <param name="attributes">attributes.</param>
        /// <param name="messagingBinding">messaging_binding.</param>
        /// <param name="roleSid">role_sid.</param>
        /// <param name="dateCreated">date_created.</param>
        /// <param name="dateUpdated">date_updated.</param>
        /// <param name="url">url.</param>
        /// <param name="lastReadMessageIndex">last_read_message_index.</param>
        /// <param name="lastReadTimestamp">last_read_timestamp.</param>
        public ServiceConversationParticipant(
            string accountSid = null,
            string chatServiceSid = null,
            string conversationSid = null,
            string sid = null,
            string identity = null,
            string attributes = null,
            object messagingBinding = null,
            string roleSid = null,
            DateTime? dateCreated = null,
            DateTime? dateUpdated = null,
            string url = null,
            int? lastReadMessageIndex = null,
            string lastReadTimestamp = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();

            if (accountSid != null)
            {
                this.AccountSid = accountSid;
            }

            if (chatServiceSid != null)
            {
                this.ChatServiceSid = chatServiceSid;
            }

            if (conversationSid != null)
            {
                this.ConversationSid = conversationSid;
            }

            if (sid != null)
            {
                this.Sid = sid;
            }

            if (identity != null)
            {
                this.Identity = identity;
            }

            if (attributes != null)
            {
                this.Attributes = attributes;
            }

            if (messagingBinding != null)
            {
                this.MessagingBinding = messagingBinding;
            }

            if (roleSid != null)
            {
                this.RoleSid = roleSid;
            }

            if (dateCreated != null)
            {
                this.DateCreated = dateCreated;
            }

            if (dateUpdated != null)
            {
                this.DateUpdated = dateUpdated;
            }

            if (url != null)
            {
                this.Url = url;
            }

            if (lastReadMessageIndex != null)
            {
                this.LastReadMessageIndex = lastReadMessageIndex;
            }

            if (lastReadTimestamp != null)
            {
                this.LastReadTimestamp = lastReadTimestamp;
            }
        }

        /// <summary>
        /// The unique ID of the [Account](https://www.twilio.com/docs/iam/api/account) responsible for this participant.
        /// </summary>
        [JsonProperty("account_sid")]
        public string AccountSid
        {
            get
            {
                return this.accountSid;
            }

            set
            {
                this.shouldSerialize["account_sid"] = true;
                this.accountSid = value;
            }
        }

        /// <summary>
        /// The SID of the [Conversation Service](https://www.twilio.com/docs/conversations/api/service-resource) the Participant resource is associated with.
        /// </summary>
        [JsonProperty("chat_service_sid")]
        public string ChatServiceSid
        {
            get
            {
                return this.chatServiceSid;
            }

            set
            {
                this.shouldSerialize["chat_service_sid"] = true;
                this.chatServiceSid = value;
            }
        }

        /// <summary>
        /// The unique ID of the [Conversation](https://www.twilio.com/docs/conversations/api/conversation-resource) for this participant.
        /// </summary>
        [JsonProperty("conversation_sid")]
        public string ConversationSid
        {
            get
            {
                return this.conversationSid;
            }

            set
            {
                this.shouldSerialize["conversation_sid"] = true;
                this.conversationSid = value;
            }
        }

        /// <summary>
        /// A 34 character string that uniquely identifies this resource.
        /// </summary>
        [JsonProperty("sid")]
        public string Sid
        {
            get
            {
                return this.sid;
            }

            set
            {
                this.shouldSerialize["sid"] = true;
                this.sid = value;
            }
        }

        /// <summary>
        /// A unique string identifier for the conversation participant as [Conversation User](https://www.twilio.com/docs/conversations/api/user-resource). This parameter is non-null if (and only if) the participant is using the [Conversation SDK](https://www.twilio.com/docs/conversations/sdk-overview) to communicate. Limited to 256 characters.
        /// </summary>
        [JsonProperty("identity")]
        public string Identity
        {
            get
            {
                return this.identity;
            }

            set
            {
                this.shouldSerialize["identity"] = true;
                this.identity = value;
            }
        }

        /// <summary>
        /// An optional string metadata field you can use to store any data you wish. The string value must contain structurally valid JSON if specified.  **Note** that if the attributes are not set `{}` will be returned.
        /// </summary>
        [JsonProperty("attributes")]
        public string Attributes
        {
            get
            {
                return this.attributes;
            }

            set
            {
                this.shouldSerialize["attributes"] = true;
                this.attributes = value;
            }
        }

        /// <summary>
        /// Information about how this participant exchanges messages with the conversation. A JSON parameter consisting of type and address fields of the participant.
        /// </summary>
        [JsonProperty("messaging_binding")]
        public object MessagingBinding
        {
            get
            {
                return this.messagingBinding;
            }

            set
            {
                this.shouldSerialize["messaging_binding"] = true;
                this.messagingBinding = value;
            }
        }

        /// <summary>
        /// The SID of a conversation-level [Role](https://www.twilio.com/docs/conversations/api/role-resource) to assign to the participant.
        /// </summary>
        [JsonProperty("role_sid")]
        public string RoleSid
        {
            get
            {
                return this.roleSid;
            }

            set
            {
                this.shouldSerialize["role_sid"] = true;
                this.roleSid = value;
            }
        }

        /// <summary>
        /// The date on which this resource was created.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("date_created")]
        public DateTime? DateCreated
        {
            get
            {
                return this.dateCreated;
            }

            set
            {
                this.shouldSerialize["date_created"] = true;
                this.dateCreated = value;
            }
        }

        /// <summary>
        /// The date on which this resource was last updated.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("date_updated")]
        public DateTime? DateUpdated
        {
            get
            {
                return this.dateUpdated;
            }

            set
            {
                this.shouldSerialize["date_updated"] = true;
                this.dateUpdated = value;
            }
        }

        /// <summary>
        /// An absolute API resource URL for this participant.
        /// </summary>
        [JsonProperty("url")]
        public string Url
        {
            get
            {
                return this.url;
            }

            set
            {
                this.shouldSerialize["url"] = true;
                this.url = value;
            }
        }

        /// <summary>
        /// Index of last “read” message in the [Conversation](https://www.twilio.com/docs/conversations/api/conversation-resource) for the Participant.
        /// </summary>
        [JsonProperty("last_read_message_index")]
        public int? LastReadMessageIndex
        {
            get
            {
                return this.lastReadMessageIndex;
            }

            set
            {
                this.shouldSerialize["last_read_message_index"] = true;
                this.lastReadMessageIndex = value;
            }
        }

        /// <summary>
        /// Timestamp of last “read” message in the [Conversation](https://www.twilio.com/docs/conversations/api/conversation-resource) for the Participant.
        /// </summary>
        [JsonProperty("last_read_timestamp")]
        public string LastReadTimestamp
        {
            get
            {
                return this.lastReadTimestamp;
            }

            set
            {
                this.shouldSerialize["last_read_timestamp"] = true;
                this.lastReadTimestamp = value;
            }
        }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ServiceConversationParticipant : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetAccountSid()
        {
            this.shouldSerialize["account_sid"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetChatServiceSid()
        {
            this.shouldSerialize["chat_service_sid"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetConversationSid()
        {
            this.shouldSerialize["conversation_sid"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetSid()
        {
            this.shouldSerialize["sid"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetIdentity()
        {
            this.shouldSerialize["identity"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetAttributes()
        {
            this.shouldSerialize["attributes"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetMessagingBinding()
        {
            this.shouldSerialize["messaging_binding"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetRoleSid()
        {
            this.shouldSerialize["role_sid"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetDateCreated()
        {
            this.shouldSerialize["date_created"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetDateUpdated()
        {
            this.shouldSerialize["date_updated"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetUrl()
        {
            this.shouldSerialize["url"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetLastReadMessageIndex()
        {
            this.shouldSerialize["last_read_message_index"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetLastReadTimestamp()
        {
            this.shouldSerialize["last_read_timestamp"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeAccountSid()
        {
            return this.shouldSerialize["account_sid"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeChatServiceSid()
        {
            return this.shouldSerialize["chat_service_sid"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeConversationSid()
        {
            return this.shouldSerialize["conversation_sid"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeSid()
        {
            return this.shouldSerialize["sid"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeIdentity()
        {
            return this.shouldSerialize["identity"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeAttributes()
        {
            return this.shouldSerialize["attributes"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeMessagingBinding()
        {
            return this.shouldSerialize["messaging_binding"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeRoleSid()
        {
            return this.shouldSerialize["role_sid"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeDateCreated()
        {
            return this.shouldSerialize["date_created"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeDateUpdated()
        {
            return this.shouldSerialize["date_updated"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeUrl()
        {
            return this.shouldSerialize["url"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeLastReadMessageIndex()
        {
            return this.shouldSerialize["last_read_message_index"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeLastReadTimestamp()
        {
            return this.shouldSerialize["last_read_timestamp"];
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"AccountSid = {this.AccountSid ?? "null"}");
            toStringOutput.Add($"ChatServiceSid = {this.ChatServiceSid ?? "null"}");
            toStringOutput.Add($"ConversationSid = {this.ConversationSid ?? "null"}");
            toStringOutput.Add($"Sid = {this.Sid ?? "null"}");
            toStringOutput.Add($"Identity = {this.Identity ?? "null"}");
            toStringOutput.Add($"Attributes = {this.Attributes ?? "null"}");
            toStringOutput.Add($"MessagingBinding = {(this.MessagingBinding == null ? "null" : this.MessagingBinding.ToString())}");
            toStringOutput.Add($"RoleSid = {this.RoleSid ?? "null"}");
            toStringOutput.Add($"DateCreated = {(this.DateCreated == null ? "null" : this.DateCreated.ToString())}");
            toStringOutput.Add($"DateUpdated = {(this.DateUpdated == null ? "null" : this.DateUpdated.ToString())}");
            toStringOutput.Add($"Url = {this.Url ?? "null"}");
            toStringOutput.Add($"LastReadMessageIndex = {(this.LastReadMessageIndex == null ? "null" : this.LastReadMessageIndex.ToString())}");
            toStringOutput.Add($"LastReadTimestamp = {this.LastReadTimestamp ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}