// <copyright file="TaskReservationCallStatus.cs" company="APIMatic">
// TwilioApIs.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace TwilioApIs.Standard.Models
{
    /// <summary>
    /// TaskReservationCallStatus.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum TaskReservationCallStatus
    {
        /// <summary>
        /// Initiated.
        /// </summary>
        [EnumMember(Value = "initiated")]
        Initiated,

        /// <summary>
        /// Ringing.
        /// </summary>
        [EnumMember(Value = "ringing")]
        Ringing,

        /// <summary>
        /// Answered.
        /// </summary>
        [EnumMember(Value = "answered")]
        Answered,

        /// <summary>
        /// Completed.
        /// </summary>
        [EnumMember(Value = "completed")]
        Completed
    }
}