// <copyright file="TaskQueue.cs" company="APIMatic">
// TwilioApIs.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using TwilioApIs.Standard.Utilities;

namespace TwilioApIs.Standard.Models
{
    /// <summary>
    /// TaskQueue.
    /// </summary>
    public class TaskQueue
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        private string accountSid;
        private string assignmentActivitySid;
        private string assignmentActivityName;
        private DateTime? dateCreated;
        private DateTime? dateUpdated;
        private string friendlyName;
        private string reservationActivitySid;
        private string reservationActivityName;
        private string sid;
        private string targetWorkers;
        private string url;
        private string workspaceSid;
        private object links;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "account_sid", false },
            { "assignment_activity_sid", false },
            { "assignment_activity_name", false },
            { "date_created", false },
            { "date_updated", false },
            { "friendly_name", false },
            { "reservation_activity_sid", false },
            { "reservation_activity_name", false },
            { "sid", false },
            { "target_workers", false },
            { "url", false },
            { "workspace_sid", false },
            { "links", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="TaskQueue"/> class.
        /// </summary>
        public TaskQueue()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TaskQueue"/> class.
        /// </summary>
        /// <param name="accountSid">account_sid.</param>
        /// <param name="assignmentActivitySid">assignment_activity_sid.</param>
        /// <param name="assignmentActivityName">assignment_activity_name.</param>
        /// <param name="dateCreated">date_created.</param>
        /// <param name="dateUpdated">date_updated.</param>
        /// <param name="friendlyName">friendly_name.</param>
        /// <param name="maxReservedWorkers">max_reserved_workers.</param>
        /// <param name="reservationActivitySid">reservation_activity_sid.</param>
        /// <param name="reservationActivityName">reservation_activity_name.</param>
        /// <param name="sid">sid.</param>
        /// <param name="targetWorkers">target_workers.</param>
        /// <param name="taskOrder">task_order.</param>
        /// <param name="url">url.</param>
        /// <param name="workspaceSid">workspace_sid.</param>
        /// <param name="links">links.</param>
        public TaskQueue(
            string accountSid = null,
            string assignmentActivitySid = null,
            string assignmentActivityName = null,
            DateTime? dateCreated = null,
            DateTime? dateUpdated = null,
            string friendlyName = null,
            int? maxReservedWorkers = 0,
            string reservationActivitySid = null,
            string reservationActivityName = null,
            string sid = null,
            string targetWorkers = null,
            Models.TaskQueueTaskOrder? taskOrder = null,
            string url = null,
            string workspaceSid = null,
            object links = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();

            if (accountSid != null)
            {
                this.AccountSid = accountSid;
            }

            if (assignmentActivitySid != null)
            {
                this.AssignmentActivitySid = assignmentActivitySid;
            }

            if (assignmentActivityName != null)
            {
                this.AssignmentActivityName = assignmentActivityName;
            }

            if (dateCreated != null)
            {
                this.DateCreated = dateCreated;
            }

            if (dateUpdated != null)
            {
                this.DateUpdated = dateUpdated;
            }

            if (friendlyName != null)
            {
                this.FriendlyName = friendlyName;
            }
            this.MaxReservedWorkers = maxReservedWorkers;

            if (reservationActivitySid != null)
            {
                this.ReservationActivitySid = reservationActivitySid;
            }

            if (reservationActivityName != null)
            {
                this.ReservationActivityName = reservationActivityName;
            }

            if (sid != null)
            {
                this.Sid = sid;
            }

            if (targetWorkers != null)
            {
                this.TargetWorkers = targetWorkers;
            }
            this.TaskOrder = taskOrder;

            if (url != null)
            {
                this.Url = url;
            }

            if (workspaceSid != null)
            {
                this.WorkspaceSid = workspaceSid;
            }

            if (links != null)
            {
                this.Links = links;
            }
        }

        /// <summary>
        /// The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the TaskQueue resource.
        /// </summary>
        [JsonProperty("account_sid")]
        public string AccountSid
        {
            get
            {
                return this.accountSid;
            }

            set
            {
                this.shouldSerialize["account_sid"] = true;
                this.accountSid = value;
            }
        }

        /// <summary>
        /// The SID of the Activity to assign Workers when a task is assigned for them.
        /// </summary>
        [JsonProperty("assignment_activity_sid")]
        public string AssignmentActivitySid
        {
            get
            {
                return this.assignmentActivitySid;
            }

            set
            {
                this.shouldSerialize["assignment_activity_sid"] = true;
                this.assignmentActivitySid = value;
            }
        }

        /// <summary>
        /// The name of the Activity to assign Workers when a task is assigned for them.
        /// </summary>
        [JsonProperty("assignment_activity_name")]
        public string AssignmentActivityName
        {
            get
            {
                return this.assignmentActivityName;
            }

            set
            {
                this.shouldSerialize["assignment_activity_name"] = true;
                this.assignmentActivityName = value;
            }
        }

        /// <summary>
        /// The date and time in GMT when the resource was created specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("date_created")]
        public DateTime? DateCreated
        {
            get
            {
                return this.dateCreated;
            }

            set
            {
                this.shouldSerialize["date_created"] = true;
                this.dateCreated = value;
            }
        }

        /// <summary>
        /// The date and time in GMT when the resource was last updated specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("date_updated")]
        public DateTime? DateUpdated
        {
            get
            {
                return this.dateUpdated;
            }

            set
            {
                this.shouldSerialize["date_updated"] = true;
                this.dateUpdated = value;
            }
        }

        /// <summary>
        /// The string that you assigned to describe the resource.
        /// </summary>
        [JsonProperty("friendly_name")]
        public string FriendlyName
        {
            get
            {
                return this.friendlyName;
            }

            set
            {
                this.shouldSerialize["friendly_name"] = true;
                this.friendlyName = value;
            }
        }

        /// <summary>
        /// The maximum number of Workers to reserve for the assignment of a task in the queue. Can be an integer between 1 and 50, inclusive and defaults to 1.
        /// </summary>
        [JsonProperty("max_reserved_workers", NullValueHandling = NullValueHandling.Ignore)]
        public int? MaxReservedWorkers { get; set; }

        /// <summary>
        /// The SID of the Activity to assign Workers once a task is reserved for them.
        /// </summary>
        [JsonProperty("reservation_activity_sid")]
        public string ReservationActivitySid
        {
            get
            {
                return this.reservationActivitySid;
            }

            set
            {
                this.shouldSerialize["reservation_activity_sid"] = true;
                this.reservationActivitySid = value;
            }
        }

        /// <summary>
        /// The name of the Activity to assign Workers once a task is reserved for them.
        /// </summary>
        [JsonProperty("reservation_activity_name")]
        public string ReservationActivityName
        {
            get
            {
                return this.reservationActivityName;
            }

            set
            {
                this.shouldSerialize["reservation_activity_name"] = true;
                this.reservationActivityName = value;
            }
        }

        /// <summary>
        /// The unique string that we created to identify the TaskQueue resource.
        /// </summary>
        [JsonProperty("sid")]
        public string Sid
        {
            get
            {
                return this.sid;
            }

            set
            {
                this.shouldSerialize["sid"] = true;
                this.sid = value;
            }
        }

        /// <summary>
        /// A string describing the Worker selection criteria for any Tasks that enter the TaskQueue. For example `'"language" == "spanish"'` If no TargetWorkers parameter is provided, Tasks will wait in the TaskQueue until they are either deleted or moved to another TaskQueue. Additional examples on how to describing Worker selection criteria below. Defaults to 1==1.
        /// </summary>
        [JsonProperty("target_workers")]
        public string TargetWorkers
        {
            get
            {
                return this.targetWorkers;
            }

            set
            {
                this.shouldSerialize["target_workers"] = true;
                this.targetWorkers = value;
            }
        }

        /// <summary>
        /// How Tasks will be assigned to Workers. Set this parameter to `LIFO` to assign most recently created Task first or `FIFO` to assign the oldest Task. Default is FIFO. [Click here](https://www.twilio.com/docs/taskrouter/queue-ordering-last-first-out-lifo) to learn more.
        /// </summary>
        [JsonProperty("task_order", NullValueHandling = NullValueHandling.Ignore)]
        public Models.TaskQueueTaskOrder? TaskOrder { get; set; }

        /// <summary>
        /// The absolute URL of the TaskQueue resource.
        /// </summary>
        [JsonProperty("url")]
        public string Url
        {
            get
            {
                return this.url;
            }

            set
            {
                this.shouldSerialize["url"] = true;
                this.url = value;
            }
        }

        /// <summary>
        /// The SID of the Workspace that contains the TaskQueue.
        /// </summary>
        [JsonProperty("workspace_sid")]
        public string WorkspaceSid
        {
            get
            {
                return this.workspaceSid;
            }

            set
            {
                this.shouldSerialize["workspace_sid"] = true;
                this.workspaceSid = value;
            }
        }

        /// <summary>
        /// The URLs of related resources.
        /// </summary>
        [JsonProperty("links")]
        public object Links
        {
            get
            {
                return this.links;
            }

            set
            {
                this.shouldSerialize["links"] = true;
                this.links = value;
            }
        }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"TaskQueue : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetAccountSid()
        {
            this.shouldSerialize["account_sid"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetAssignmentActivitySid()
        {
            this.shouldSerialize["assignment_activity_sid"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetAssignmentActivityName()
        {
            this.shouldSerialize["assignment_activity_name"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetDateCreated()
        {
            this.shouldSerialize["date_created"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetDateUpdated()
        {
            this.shouldSerialize["date_updated"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetFriendlyName()
        {
            this.shouldSerialize["friendly_name"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetReservationActivitySid()
        {
            this.shouldSerialize["reservation_activity_sid"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetReservationActivityName()
        {
            this.shouldSerialize["reservation_activity_name"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetSid()
        {
            this.shouldSerialize["sid"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetTargetWorkers()
        {
            this.shouldSerialize["target_workers"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetUrl()
        {
            this.shouldSerialize["url"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetWorkspaceSid()
        {
            this.shouldSerialize["workspace_sid"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetLinks()
        {
            this.shouldSerialize["links"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeAccountSid()
        {
            return this.shouldSerialize["account_sid"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeAssignmentActivitySid()
        {
            return this.shouldSerialize["assignment_activity_sid"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeAssignmentActivityName()
        {
            return this.shouldSerialize["assignment_activity_name"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeDateCreated()
        {
            return this.shouldSerialize["date_created"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeDateUpdated()
        {
            return this.shouldSerialize["date_updated"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeFriendlyName()
        {
            return this.shouldSerialize["friendly_name"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeReservationActivitySid()
        {
            return this.shouldSerialize["reservation_activity_sid"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeReservationActivityName()
        {
            return this.shouldSerialize["reservation_activity_name"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeSid()
        {
            return this.shouldSerialize["sid"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeTargetWorkers()
        {
            return this.shouldSerialize["target_workers"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeUrl()
        {
            return this.shouldSerialize["url"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeWorkspaceSid()
        {
            return this.shouldSerialize["workspace_sid"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeLinks()
        {
            return this.shouldSerialize["links"];
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"AccountSid = {this.AccountSid ?? "null"}");
            toStringOutput.Add($"AssignmentActivitySid = {this.AssignmentActivitySid ?? "null"}");
            toStringOutput.Add($"AssignmentActivityName = {this.AssignmentActivityName ?? "null"}");
            toStringOutput.Add($"DateCreated = {(this.DateCreated == null ? "null" : this.DateCreated.ToString())}");
            toStringOutput.Add($"DateUpdated = {(this.DateUpdated == null ? "null" : this.DateUpdated.ToString())}");
            toStringOutput.Add($"FriendlyName = {this.FriendlyName ?? "null"}");
            toStringOutput.Add($"MaxReservedWorkers = {(this.MaxReservedWorkers == null ? "null" : this.MaxReservedWorkers.ToString())}");
            toStringOutput.Add($"ReservationActivitySid = {this.ReservationActivitySid ?? "null"}");
            toStringOutput.Add($"ReservationActivityName = {this.ReservationActivityName ?? "null"}");
            toStringOutput.Add($"Sid = {this.Sid ?? "null"}");
            toStringOutput.Add($"TargetWorkers = {this.TargetWorkers ?? "null"}");
            toStringOutput.Add($"TaskOrder = {(this.TaskOrder == null ? "null" : this.TaskOrder.ToString())}");
            toStringOutput.Add($"Url = {this.Url ?? "null"}");
            toStringOutput.Add($"WorkspaceSid = {this.WorkspaceSid ?? "null"}");
            toStringOutput.Add($"Links = {(this.Links == null ? "null" : this.Links.ToString())}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}