// <copyright file="TaskReservation.cs" company="APIMatic">
// TwilioApIs.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using TwilioApIs.Standard.Utilities;

namespace TwilioApIs.Standard.Models
{
    /// <summary>
    /// TaskReservation.
    /// </summary>
    public class TaskReservation
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        private string accountSid;
        private DateTime? dateCreated;
        private DateTime? dateUpdated;
        private string sid;
        private string taskSid;
        private string workerName;
        private string workerSid;
        private string workspaceSid;
        private string url;
        private object links;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "account_sid", false },
            { "date_created", false },
            { "date_updated", false },
            { "sid", false },
            { "task_sid", false },
            { "worker_name", false },
            { "worker_sid", false },
            { "workspace_sid", false },
            { "url", false },
            { "links", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="TaskReservation"/> class.
        /// </summary>
        public TaskReservation()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TaskReservation"/> class.
        /// </summary>
        /// <param name="accountSid">account_sid.</param>
        /// <param name="dateCreated">date_created.</param>
        /// <param name="dateUpdated">date_updated.</param>
        /// <param name="reservationStatus">reservation_status.</param>
        /// <param name="sid">sid.</param>
        /// <param name="taskSid">task_sid.</param>
        /// <param name="workerName">worker_name.</param>
        /// <param name="workerSid">worker_sid.</param>
        /// <param name="workspaceSid">workspace_sid.</param>
        /// <param name="url">url.</param>
        /// <param name="links">links.</param>
        public TaskReservation(
            string accountSid = null,
            DateTime? dateCreated = null,
            DateTime? dateUpdated = null,
            Models.TaskReservationStatus? reservationStatus = null,
            string sid = null,
            string taskSid = null,
            string workerName = null,
            string workerSid = null,
            string workspaceSid = null,
            string url = null,
            object links = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();

            if (accountSid != null)
            {
                this.AccountSid = accountSid;
            }

            if (dateCreated != null)
            {
                this.DateCreated = dateCreated;
            }

            if (dateUpdated != null)
            {
                this.DateUpdated = dateUpdated;
            }
            this.ReservationStatus = reservationStatus;

            if (sid != null)
            {
                this.Sid = sid;
            }

            if (taskSid != null)
            {
                this.TaskSid = taskSid;
            }

            if (workerName != null)
            {
                this.WorkerName = workerName;
            }

            if (workerSid != null)
            {
                this.WorkerSid = workerSid;
            }

            if (workspaceSid != null)
            {
                this.WorkspaceSid = workspaceSid;
            }

            if (url != null)
            {
                this.Url = url;
            }

            if (links != null)
            {
                this.Links = links;
            }
        }

        /// <summary>
        /// The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the TaskReservation resource.
        /// </summary>
        [JsonProperty("account_sid")]
        public string AccountSid
        {
            get
            {
                return this.accountSid;
            }

            set
            {
                this.shouldSerialize["account_sid"] = true;
                this.accountSid = value;
            }
        }

        /// <summary>
        /// The date and time in GMT when the resource was created specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("date_created")]
        public DateTime? DateCreated
        {
            get
            {
                return this.dateCreated;
            }

            set
            {
                this.shouldSerialize["date_created"] = true;
                this.dateCreated = value;
            }
        }

        /// <summary>
        /// The date and time in GMT when the resource was last updated specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("date_updated")]
        public DateTime? DateUpdated
        {
            get
            {
                return this.dateUpdated;
            }

            set
            {
                this.shouldSerialize["date_updated"] = true;
                this.dateUpdated = value;
            }
        }

        /// <summary>
        /// The current status of the reservation. Can be: `pending`, `accepted`, `rejected`, or `timeout`.
        /// </summary>
        [JsonProperty("reservation_status", NullValueHandling = NullValueHandling.Ignore)]
        public Models.TaskReservationStatus? ReservationStatus { get; set; }

        /// <summary>
        /// The unique string that we created to identify the TaskReservation resource.
        /// </summary>
        [JsonProperty("sid")]
        public string Sid
        {
            get
            {
                return this.sid;
            }

            set
            {
                this.shouldSerialize["sid"] = true;
                this.sid = value;
            }
        }

        /// <summary>
        /// The SID of the reserved Task resource.
        /// </summary>
        [JsonProperty("task_sid")]
        public string TaskSid
        {
            get
            {
                return this.taskSid;
            }

            set
            {
                this.shouldSerialize["task_sid"] = true;
                this.taskSid = value;
            }
        }

        /// <summary>
        /// The `friendly_name` of the Worker that is reserved.
        /// </summary>
        [JsonProperty("worker_name")]
        public string WorkerName
        {
            get
            {
                return this.workerName;
            }

            set
            {
                this.shouldSerialize["worker_name"] = true;
                this.workerName = value;
            }
        }

        /// <summary>
        /// The SID of the reserved Worker resource.
        /// </summary>
        [JsonProperty("worker_sid")]
        public string WorkerSid
        {
            get
            {
                return this.workerSid;
            }

            set
            {
                this.shouldSerialize["worker_sid"] = true;
                this.workerSid = value;
            }
        }

        /// <summary>
        /// The SID of the Workspace that this task is contained within.
        /// </summary>
        [JsonProperty("workspace_sid")]
        public string WorkspaceSid
        {
            get
            {
                return this.workspaceSid;
            }

            set
            {
                this.shouldSerialize["workspace_sid"] = true;
                this.workspaceSid = value;
            }
        }

        /// <summary>
        /// The absolute URL of the TaskReservation reservation.
        /// </summary>
        [JsonProperty("url")]
        public string Url
        {
            get
            {
                return this.url;
            }

            set
            {
                this.shouldSerialize["url"] = true;
                this.url = value;
            }
        }

        /// <summary>
        /// The URLs of related resources.
        /// </summary>
        [JsonProperty("links")]
        public object Links
        {
            get
            {
                return this.links;
            }

            set
            {
                this.shouldSerialize["links"] = true;
                this.links = value;
            }
        }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"TaskReservation : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetAccountSid()
        {
            this.shouldSerialize["account_sid"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetDateCreated()
        {
            this.shouldSerialize["date_created"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetDateUpdated()
        {
            this.shouldSerialize["date_updated"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetSid()
        {
            this.shouldSerialize["sid"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetTaskSid()
        {
            this.shouldSerialize["task_sid"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetWorkerName()
        {
            this.shouldSerialize["worker_name"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetWorkerSid()
        {
            this.shouldSerialize["worker_sid"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetWorkspaceSid()
        {
            this.shouldSerialize["workspace_sid"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetUrl()
        {
            this.shouldSerialize["url"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetLinks()
        {
            this.shouldSerialize["links"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeAccountSid()
        {
            return this.shouldSerialize["account_sid"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeDateCreated()
        {
            return this.shouldSerialize["date_created"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeDateUpdated()
        {
            return this.shouldSerialize["date_updated"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeSid()
        {
            return this.shouldSerialize["sid"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeTaskSid()
        {
            return this.shouldSerialize["task_sid"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeWorkerName()
        {
            return this.shouldSerialize["worker_name"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeWorkerSid()
        {
            return this.shouldSerialize["worker_sid"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeWorkspaceSid()
        {
            return this.shouldSerialize["workspace_sid"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeUrl()
        {
            return this.shouldSerialize["url"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeLinks()
        {
            return this.shouldSerialize["links"];
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"AccountSid = {this.AccountSid ?? "null"}");
            toStringOutput.Add($"DateCreated = {(this.DateCreated == null ? "null" : this.DateCreated.ToString())}");
            toStringOutput.Add($"DateUpdated = {(this.DateUpdated == null ? "null" : this.DateUpdated.ToString())}");
            toStringOutput.Add($"ReservationStatus = {(this.ReservationStatus == null ? "null" : this.ReservationStatus.ToString())}");
            toStringOutput.Add($"Sid = {this.Sid ?? "null"}");
            toStringOutput.Add($"TaskSid = {this.TaskSid ?? "null"}");
            toStringOutput.Add($"WorkerName = {this.WorkerName ?? "null"}");
            toStringOutput.Add($"WorkerSid = {this.WorkerSid ?? "null"}");
            toStringOutput.Add($"WorkspaceSid = {this.WorkspaceSid ?? "null"}");
            toStringOutput.Add($"Url = {this.Url ?? "null"}");
            toStringOutput.Add($"Links = {(this.Links == null ? "null" : this.Links.ToString())}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}