// <copyright file="TaskQueuesStats.cs" company="APIMatic">
// TwilioApIs.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using TwilioApIs.Standard.Utilities;

namespace TwilioApIs.Standard.Models
{
    /// <summary>
    /// TaskQueuesStats.
    /// </summary>
    public class TaskQueuesStats
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        private string accountSid;
        private object cumulative;
        private object realtime;
        private string taskQueueSid;
        private string workspaceSid;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "account_sid", false },
            { "cumulative", false },
            { "realtime", false },
            { "task_queue_sid", false },
            { "workspace_sid", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="TaskQueuesStats"/> class.
        /// </summary>
        public TaskQueuesStats()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TaskQueuesStats"/> class.
        /// </summary>
        /// <param name="accountSid">account_sid.</param>
        /// <param name="cumulative">cumulative.</param>
        /// <param name="realtime">realtime.</param>
        /// <param name="taskQueueSid">task_queue_sid.</param>
        /// <param name="workspaceSid">workspace_sid.</param>
        public TaskQueuesStats(
            string accountSid = null,
            object cumulative = null,
            object realtime = null,
            string taskQueueSid = null,
            string workspaceSid = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();

            if (accountSid != null)
            {
                this.AccountSid = accountSid;
            }

            if (cumulative != null)
            {
                this.Cumulative = cumulative;
            }

            if (realtime != null)
            {
                this.Realtime = realtime;
            }

            if (taskQueueSid != null)
            {
                this.TaskQueueSid = taskQueueSid;
            }

            if (workspaceSid != null)
            {
                this.WorkspaceSid = workspaceSid;
            }
        }

        /// <summary>
        /// The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the TaskQueue resource.
        /// </summary>
        [JsonProperty("account_sid")]
        public string AccountSid
        {
            get
            {
                return this.accountSid;
            }

            set
            {
                this.shouldSerialize["account_sid"] = true;
                this.accountSid = value;
            }
        }

        /// <summary>
        /// An object that contains the cumulative statistics for the TaskQueues.
        /// </summary>
        [JsonProperty("cumulative")]
        public object Cumulative
        {
            get
            {
                return this.cumulative;
            }

            set
            {
                this.shouldSerialize["cumulative"] = true;
                this.cumulative = value;
            }
        }

        /// <summary>
        /// An object that contains the real-time statistics for the TaskQueues.
        /// </summary>
        [JsonProperty("realtime")]
        public object Realtime
        {
            get
            {
                return this.realtime;
            }

            set
            {
                this.shouldSerialize["realtime"] = true;
                this.realtime = value;
            }
        }

        /// <summary>
        /// The SID of the TaskQueue from which these statistics were calculated.
        /// </summary>
        [JsonProperty("task_queue_sid")]
        public string TaskQueueSid
        {
            get
            {
                return this.taskQueueSid;
            }

            set
            {
                this.shouldSerialize["task_queue_sid"] = true;
                this.taskQueueSid = value;
            }
        }

        /// <summary>
        /// The SID of the Workspace that contains the TaskQueues.
        /// </summary>
        [JsonProperty("workspace_sid")]
        public string WorkspaceSid
        {
            get
            {
                return this.workspaceSid;
            }

            set
            {
                this.shouldSerialize["workspace_sid"] = true;
                this.workspaceSid = value;
            }
        }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"TaskQueuesStats : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetAccountSid()
        {
            this.shouldSerialize["account_sid"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetCumulative()
        {
            this.shouldSerialize["cumulative"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetRealtime()
        {
            this.shouldSerialize["realtime"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetTaskQueueSid()
        {
            this.shouldSerialize["task_queue_sid"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetWorkspaceSid()
        {
            this.shouldSerialize["workspace_sid"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeAccountSid()
        {
            return this.shouldSerialize["account_sid"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeCumulative()
        {
            return this.shouldSerialize["cumulative"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeRealtime()
        {
            return this.shouldSerialize["realtime"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeTaskQueueSid()
        {
            return this.shouldSerialize["task_queue_sid"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeWorkspaceSid()
        {
            return this.shouldSerialize["workspace_sid"];
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"AccountSid = {this.AccountSid ?? "null"}");
            toStringOutput.Add($"Cumulative = {(this.Cumulative == null ? "null" : this.Cumulative.ToString())}");
            toStringOutput.Add($"Realtime = {(this.Realtime == null ? "null" : this.Realtime.ToString())}");
            toStringOutput.Add($"TaskQueueSid = {this.TaskQueueSid ?? "null"}");
            toStringOutput.Add($"WorkspaceSid = {this.WorkspaceSid ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}