// <copyright file="VerificationEnumStatus.cs" company="APIMatic">
// TwilioApIs.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace TwilioApIs.Standard.Models
{
    /// <summary>
    /// VerificationEnumStatus.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum VerificationEnumStatus
    {
        /// <summary>
        /// Canceled.
        /// </summary>
        [EnumMember(Value = "canceled")]
        Canceled,

        /// <summary>
        /// Approved.
        /// </summary>
        [EnumMember(Value = "approved")]
        Approved
    }
}