// <copyright file="VerificationAttemptEnumChannels.cs" company="APIMatic">
// TwilioApIs.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace TwilioApIs.Standard.Models
{
    /// <summary>
    /// VerificationAttemptEnumChannels.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum VerificationAttemptEnumChannels
    {
        /// <summary>
        /// Sms.
        /// </summary>
        [EnumMember(Value = "sms")]
        Sms,

        /// <summary>
        /// Call.
        /// </summary>
        [EnumMember(Value = "call")]
        Call,

        /// <summary>
        /// Email.
        /// </summary>
        [EnumMember(Value = "email")]
        Email,

        /// <summary>
        /// Whatsapp.
        /// </summary>
        [EnumMember(Value = "whatsapp")]
        Whatsapp,

        /// <summary>
        /// Rbm.
        /// </summary>
        [EnumMember(Value = "rbm")]
        Rbm
    }
}