// <copyright file="Webhook.cs" company="APIMatic">
// TwilioApIs.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using TwilioApIs.Standard.Utilities;

namespace TwilioApIs.Standard.Models
{
    /// <summary>
    /// Webhook.
    /// </summary>
    public class Webhook
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        private string sid;
        private string serviceSid;
        private string accountSid;
        private string friendlyName;
        private List<string> eventTypes;
        private string webhookUrl;
        private DateTime? dateCreated;
        private DateTime? dateUpdated;
        private string url;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "sid", false },
            { "service_sid", false },
            { "account_sid", false },
            { "friendly_name", false },
            { "event_types", false },
            { "webhook_url", false },
            { "date_created", false },
            { "date_updated", false },
            { "url", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="Webhook"/> class.
        /// </summary>
        public Webhook()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Webhook"/> class.
        /// </summary>
        /// <param name="sid">sid.</param>
        /// <param name="serviceSid">service_sid.</param>
        /// <param name="accountSid">account_sid.</param>
        /// <param name="friendlyName">friendly_name.</param>
        /// <param name="eventTypes">event_types.</param>
        /// <param name="status">status.</param>
        /// <param name="version">version.</param>
        /// <param name="webhookUrl">webhook_url.</param>
        /// <param name="webhookMethod">webhook_method.</param>
        /// <param name="dateCreated">date_created.</param>
        /// <param name="dateUpdated">date_updated.</param>
        /// <param name="url">url.</param>
        public Webhook(
            string sid = null,
            string serviceSid = null,
            string accountSid = null,
            string friendlyName = null,
            List<string> eventTypes = null,
            Models.WebhookEnumStatus? status = null,
            Models.WebhookEnumVersion? version = null,
            string webhookUrl = null,
            Models.ConfigurationWebhookMethod? webhookMethod = null,
            DateTime? dateCreated = null,
            DateTime? dateUpdated = null,
            string url = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();

            if (sid != null)
            {
                this.Sid = sid;
            }

            if (serviceSid != null)
            {
                this.ServiceSid = serviceSid;
            }

            if (accountSid != null)
            {
                this.AccountSid = accountSid;
            }

            if (friendlyName != null)
            {
                this.FriendlyName = friendlyName;
            }

            if (eventTypes != null)
            {
                this.EventTypes = eventTypes;
            }
            this.Status = status;
            this.Version = version;

            if (webhookUrl != null)
            {
                this.WebhookUrl = webhookUrl;
            }
            this.WebhookMethod = webhookMethod;

            if (dateCreated != null)
            {
                this.DateCreated = dateCreated;
            }

            if (dateUpdated != null)
            {
                this.DateUpdated = dateUpdated;
            }

            if (url != null)
            {
                this.Url = url;
            }
        }

        /// <summary>
        /// The unique string that we created to identify the Webhook resource.
        /// </summary>
        [JsonProperty("sid")]
        public string Sid
        {
            get
            {
                return this.sid;
            }

            set
            {
                this.shouldSerialize["sid"] = true;
                this.sid = value;
            }
        }

        /// <summary>
        /// The unique SID identifier of the Service.
        /// </summary>
        [JsonProperty("service_sid")]
        public string ServiceSid
        {
            get
            {
                return this.serviceSid;
            }

            set
            {
                this.shouldSerialize["service_sid"] = true;
                this.serviceSid = value;
            }
        }

        /// <summary>
        /// The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Service resource.
        /// </summary>
        [JsonProperty("account_sid")]
        public string AccountSid
        {
            get
            {
                return this.accountSid;
            }

            set
            {
                this.shouldSerialize["account_sid"] = true;
                this.accountSid = value;
            }
        }

        /// <summary>
        /// The string that you assigned to describe the webhook. **This value should not contain PII.**
        /// </summary>
        [JsonProperty("friendly_name")]
        public string FriendlyName
        {
            get
            {
                return this.friendlyName;
            }

            set
            {
                this.shouldSerialize["friendly_name"] = true;
                this.friendlyName = value;
            }
        }

        /// <summary>
        /// The array of events that this Webhook is subscribed to. Possible event types: `*, factor.deleted, factor.created, factor.verified, challenge.approved, challenge.denied`
        /// </summary>
        [JsonProperty("event_types")]
        public List<string> EventTypes
        {
            get
            {
                return this.eventTypes;
            }

            set
            {
                this.shouldSerialize["event_types"] = true;
                this.eventTypes = value;
            }
        }

        /// <summary>
        /// The webhook status. Default value is `enabled`. One of: `enabled` or `disabled`
        /// </summary>
        [JsonProperty("status", NullValueHandling = NullValueHandling.Ignore)]
        public Models.WebhookEnumStatus? Status { get; set; }

        /// <summary>
        /// The webhook version. Default value is `v2` which includes all the latest fields. Version `v1` is legacy and may be removed in the future.
        /// </summary>
        [JsonProperty("version", NullValueHandling = NullValueHandling.Ignore)]
        public Models.WebhookEnumVersion? Version { get; set; }

        /// <summary>
        /// The URL associated with this Webhook.
        /// </summary>
        [JsonProperty("webhook_url")]
        public string WebhookUrl
        {
            get
            {
                return this.webhookUrl;
            }

            set
            {
                this.shouldSerialize["webhook_url"] = true;
                this.webhookUrl = value;
            }
        }

        /// <summary>
        /// The method to be used when calling the webhook's URL.
        /// </summary>
        [JsonProperty("webhook_method", NullValueHandling = NullValueHandling.Ignore)]
        public Models.ConfigurationWebhookMethod? WebhookMethod { get; set; }

        /// <summary>
        /// The date and time in GMT when the resource was created specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("date_created")]
        public DateTime? DateCreated
        {
            get
            {
                return this.dateCreated;
            }

            set
            {
                this.shouldSerialize["date_created"] = true;
                this.dateCreated = value;
            }
        }

        /// <summary>
        /// The date and time in GMT when the resource was last updated specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("date_updated")]
        public DateTime? DateUpdated
        {
            get
            {
                return this.dateUpdated;
            }

            set
            {
                this.shouldSerialize["date_updated"] = true;
                this.dateUpdated = value;
            }
        }

        /// <summary>
        /// The absolute URL of the Webhook resource.
        /// </summary>
        [JsonProperty("url")]
        public string Url
        {
            get
            {
                return this.url;
            }

            set
            {
                this.shouldSerialize["url"] = true;
                this.url = value;
            }
        }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"Webhook : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetSid()
        {
            this.shouldSerialize["sid"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetServiceSid()
        {
            this.shouldSerialize["service_sid"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetAccountSid()
        {
            this.shouldSerialize["account_sid"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetFriendlyName()
        {
            this.shouldSerialize["friendly_name"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetEventTypes()
        {
            this.shouldSerialize["event_types"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetWebhookUrl()
        {
            this.shouldSerialize["webhook_url"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetDateCreated()
        {
            this.shouldSerialize["date_created"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetDateUpdated()
        {
            this.shouldSerialize["date_updated"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetUrl()
        {
            this.shouldSerialize["url"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeSid()
        {
            return this.shouldSerialize["sid"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeServiceSid()
        {
            return this.shouldSerialize["service_sid"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeAccountSid()
        {
            return this.shouldSerialize["account_sid"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeFriendlyName()
        {
            return this.shouldSerialize["friendly_name"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeEventTypes()
        {
            return this.shouldSerialize["event_types"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeWebhookUrl()
        {
            return this.shouldSerialize["webhook_url"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeDateCreated()
        {
            return this.shouldSerialize["date_created"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeDateUpdated()
        {
            return this.shouldSerialize["date_updated"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeUrl()
        {
            return this.shouldSerialize["url"];
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Sid = {this.Sid ?? "null"}");
            toStringOutput.Add($"ServiceSid = {this.ServiceSid ?? "null"}");
            toStringOutput.Add($"AccountSid = {this.AccountSid ?? "null"}");
            toStringOutput.Add($"FriendlyName = {this.FriendlyName ?? "null"}");
            toStringOutput.Add($"EventTypes = {(this.EventTypes == null ? "null" : $"[{string.Join(", ", this.EventTypes)} ]")}");
            toStringOutput.Add($"Status = {(this.Status == null ? "null" : this.Status.ToString())}");
            toStringOutput.Add($"Version = {(this.Version == null ? "null" : this.Version.ToString())}");
            toStringOutput.Add($"WebhookUrl = {this.WebhookUrl ?? "null"}");
            toStringOutput.Add($"WebhookMethod = {(this.WebhookMethod == null ? "null" : this.WebhookMethod.ToString())}");
            toStringOutput.Add($"DateCreated = {(this.DateCreated == null ? "null" : this.DateCreated.ToString())}");
            toStringOutput.Add($"DateUpdated = {(this.DateUpdated == null ? "null" : this.DateUpdated.ToString())}");
            toStringOutput.Add($"Url = {this.Url ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}