// <copyright file="WorkerChannel.cs" company="APIMatic">
// TwilioApIs.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using TwilioApIs.Standard.Utilities;

namespace TwilioApIs.Standard.Models
{
    /// <summary>
    /// WorkerChannel.
    /// </summary>
    public class WorkerChannel
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        private string accountSid;
        private bool? available;
        private DateTime? dateCreated;
        private DateTime? dateUpdated;
        private string sid;
        private string taskChannelSid;
        private string taskChannelUniqueName;
        private string workerSid;
        private string workspaceSid;
        private string url;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "account_sid", false },
            { "available", false },
            { "date_created", false },
            { "date_updated", false },
            { "sid", false },
            { "task_channel_sid", false },
            { "task_channel_unique_name", false },
            { "worker_sid", false },
            { "workspace_sid", false },
            { "url", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="WorkerChannel"/> class.
        /// </summary>
        public WorkerChannel()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WorkerChannel"/> class.
        /// </summary>
        /// <param name="accountSid">account_sid.</param>
        /// <param name="assignedTasks">assigned_tasks.</param>
        /// <param name="available">available.</param>
        /// <param name="availableCapacityPercentage">available_capacity_percentage.</param>
        /// <param name="configuredCapacity">configured_capacity.</param>
        /// <param name="dateCreated">date_created.</param>
        /// <param name="dateUpdated">date_updated.</param>
        /// <param name="sid">sid.</param>
        /// <param name="taskChannelSid">task_channel_sid.</param>
        /// <param name="taskChannelUniqueName">task_channel_unique_name.</param>
        /// <param name="workerSid">worker_sid.</param>
        /// <param name="workspaceSid">workspace_sid.</param>
        /// <param name="url">url.</param>
        public WorkerChannel(
            string accountSid = null,
            int? assignedTasks = 0,
            bool? available = null,
            int? availableCapacityPercentage = 0,
            int? configuredCapacity = 0,
            DateTime? dateCreated = null,
            DateTime? dateUpdated = null,
            string sid = null,
            string taskChannelSid = null,
            string taskChannelUniqueName = null,
            string workerSid = null,
            string workspaceSid = null,
            string url = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();

            if (accountSid != null)
            {
                this.AccountSid = accountSid;
            }
            this.AssignedTasks = assignedTasks;

            if (available != null)
            {
                this.Available = available;
            }
            this.AvailableCapacityPercentage = availableCapacityPercentage;
            this.ConfiguredCapacity = configuredCapacity;

            if (dateCreated != null)
            {
                this.DateCreated = dateCreated;
            }

            if (dateUpdated != null)
            {
                this.DateUpdated = dateUpdated;
            }

            if (sid != null)
            {
                this.Sid = sid;
            }

            if (taskChannelSid != null)
            {
                this.TaskChannelSid = taskChannelSid;
            }

            if (taskChannelUniqueName != null)
            {
                this.TaskChannelUniqueName = taskChannelUniqueName;
            }

            if (workerSid != null)
            {
                this.WorkerSid = workerSid;
            }

            if (workspaceSid != null)
            {
                this.WorkspaceSid = workspaceSid;
            }

            if (url != null)
            {
                this.Url = url;
            }
        }

        /// <summary>
        /// The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Worker resource.
        /// </summary>
        [JsonProperty("account_sid")]
        public string AccountSid
        {
            get
            {
                return this.accountSid;
            }

            set
            {
                this.shouldSerialize["account_sid"] = true;
                this.accountSid = value;
            }
        }

        /// <summary>
        /// The total number of Tasks assigned to Worker for the TaskChannel type.
        /// </summary>
        [JsonProperty("assigned_tasks", NullValueHandling = NullValueHandling.Ignore)]
        public int? AssignedTasks { get; set; }

        /// <summary>
        /// Whether the Worker should receive Tasks of the TaskChannel type.
        /// </summary>
        [JsonProperty("available")]
        public bool? Available
        {
            get
            {
                return this.available;
            }

            set
            {
                this.shouldSerialize["available"] = true;
                this.available = value;
            }
        }

        /// <summary>
        /// The current percentage of capacity the TaskChannel has available. Can be a number between `0` and `100`. A value of `0` indicates that TaskChannel has no capacity available and a value of `100` means the  Worker is available to receive any Tasks of this TaskChannel type.
        /// </summary>
        [JsonProperty("available_capacity_percentage", NullValueHandling = NullValueHandling.Ignore)]
        public int? AvailableCapacityPercentage { get; set; }

        /// <summary>
        /// The current configured capacity for the WorkerChannel. TaskRouter will not create any reservations after the assigned Tasks for the Worker reaches the value.
        /// </summary>
        [JsonProperty("configured_capacity", NullValueHandling = NullValueHandling.Ignore)]
        public int? ConfiguredCapacity { get; set; }

        /// <summary>
        /// The date and time in GMT when the resource was created specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("date_created")]
        public DateTime? DateCreated
        {
            get
            {
                return this.dateCreated;
            }

            set
            {
                this.shouldSerialize["date_created"] = true;
                this.dateCreated = value;
            }
        }

        /// <summary>
        /// The date and time in GMT when the resource was last updated specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("date_updated")]
        public DateTime? DateUpdated
        {
            get
            {
                return this.dateUpdated;
            }

            set
            {
                this.shouldSerialize["date_updated"] = true;
                this.dateUpdated = value;
            }
        }

        /// <summary>
        /// The unique string that we created to identify the WorkerChannel resource.
        /// </summary>
        [JsonProperty("sid")]
        public string Sid
        {
            get
            {
                return this.sid;
            }

            set
            {
                this.shouldSerialize["sid"] = true;
                this.sid = value;
            }
        }

        /// <summary>
        /// The SID of the TaskChannel.
        /// </summary>
        [JsonProperty("task_channel_sid")]
        public string TaskChannelSid
        {
            get
            {
                return this.taskChannelSid;
            }

            set
            {
                this.shouldSerialize["task_channel_sid"] = true;
                this.taskChannelSid = value;
            }
        }

        /// <summary>
        /// The unique name of the TaskChannel, such as `voice` or `sms`.
        /// </summary>
        [JsonProperty("task_channel_unique_name")]
        public string TaskChannelUniqueName
        {
            get
            {
                return this.taskChannelUniqueName;
            }

            set
            {
                this.shouldSerialize["task_channel_unique_name"] = true;
                this.taskChannelUniqueName = value;
            }
        }

        /// <summary>
        /// The SID of the Worker that contains the WorkerChannel.
        /// </summary>
        [JsonProperty("worker_sid")]
        public string WorkerSid
        {
            get
            {
                return this.workerSid;
            }

            set
            {
                this.shouldSerialize["worker_sid"] = true;
                this.workerSid = value;
            }
        }

        /// <summary>
        /// The SID of the Workspace that contains the WorkerChannel.
        /// </summary>
        [JsonProperty("workspace_sid")]
        public string WorkspaceSid
        {
            get
            {
                return this.workspaceSid;
            }

            set
            {
                this.shouldSerialize["workspace_sid"] = true;
                this.workspaceSid = value;
            }
        }

        /// <summary>
        /// The absolute URL of the WorkerChannel resource.
        /// </summary>
        [JsonProperty("url")]
        public string Url
        {
            get
            {
                return this.url;
            }

            set
            {
                this.shouldSerialize["url"] = true;
                this.url = value;
            }
        }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"WorkerChannel : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetAccountSid()
        {
            this.shouldSerialize["account_sid"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetAvailable()
        {
            this.shouldSerialize["available"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetDateCreated()
        {
            this.shouldSerialize["date_created"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetDateUpdated()
        {
            this.shouldSerialize["date_updated"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetSid()
        {
            this.shouldSerialize["sid"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetTaskChannelSid()
        {
            this.shouldSerialize["task_channel_sid"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetTaskChannelUniqueName()
        {
            this.shouldSerialize["task_channel_unique_name"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetWorkerSid()
        {
            this.shouldSerialize["worker_sid"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetWorkspaceSid()
        {
            this.shouldSerialize["workspace_sid"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetUrl()
        {
            this.shouldSerialize["url"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeAccountSid()
        {
            return this.shouldSerialize["account_sid"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeAvailable()
        {
            return this.shouldSerialize["available"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeDateCreated()
        {
            return this.shouldSerialize["date_created"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeDateUpdated()
        {
            return this.shouldSerialize["date_updated"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeSid()
        {
            return this.shouldSerialize["sid"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeTaskChannelSid()
        {
            return this.shouldSerialize["task_channel_sid"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeTaskChannelUniqueName()
        {
            return this.shouldSerialize["task_channel_unique_name"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeWorkerSid()
        {
            return this.shouldSerialize["worker_sid"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeWorkspaceSid()
        {
            return this.shouldSerialize["workspace_sid"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeUrl()
        {
            return this.shouldSerialize["url"];
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"AccountSid = {this.AccountSid ?? "null"}");
            toStringOutput.Add($"AssignedTasks = {(this.AssignedTasks == null ? "null" : this.AssignedTasks.ToString())}");
            toStringOutput.Add($"Available = {(this.Available == null ? "null" : this.Available.ToString())}");
            toStringOutput.Add($"AvailableCapacityPercentage = {(this.AvailableCapacityPercentage == null ? "null" : this.AvailableCapacityPercentage.ToString())}");
            toStringOutput.Add($"ConfiguredCapacity = {(this.ConfiguredCapacity == null ? "null" : this.ConfiguredCapacity.ToString())}");
            toStringOutput.Add($"DateCreated = {(this.DateCreated == null ? "null" : this.DateCreated.ToString())}");
            toStringOutput.Add($"DateUpdated = {(this.DateUpdated == null ? "null" : this.DateUpdated.ToString())}");
            toStringOutput.Add($"Sid = {this.Sid ?? "null"}");
            toStringOutput.Add($"TaskChannelSid = {this.TaskChannelSid ?? "null"}");
            toStringOutput.Add($"TaskChannelUniqueName = {this.TaskChannelUniqueName ?? "null"}");
            toStringOutput.Add($"WorkerSid = {this.WorkerSid ?? "null"}");
            toStringOutput.Add($"WorkspaceSid = {this.WorkspaceSid ?? "null"}");
            toStringOutput.Add($"Url = {this.Url ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}