// <copyright file="NotifyV1NotificationApi.cs" company="APIMatic">
// TwilioApIs.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core;
using APIMatic.Core.Utilities;
using System.Collections.Generic;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using TwilioApIs.Standard.Http.Response;

namespace TwilioApIs.Standard.Apis
{
    /// <summary>
    /// NotifyV1NotificationApi.
    /// </summary>
    public class NotifyV1NotificationApi : BaseApi
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NotifyV1NotificationApi"/> class.
        /// </summary>
        internal NotifyV1NotificationApi(GlobalConfiguration globalConfiguration) : base(globalConfiguration) { }

        /// <summary>
        /// CreateNotification EndPoint.
        /// </summary>
        /// <param name="serviceSid">Required parameter: The SID of the [Service](https://www.twilio.com/docs/notify/api/service-resource) to create the resource under..</param>
        /// <param name="body">Optional parameter: The notification text. For FCM and GCM, translates to `data.twi_body`. For APNS, translates to `aps.alert.body`. For SMS, translates to `body`. SMS requires either this `body` value, or `media_urls` attribute defined in the `sms` parameter of the notification..</param>
        /// <param name="priority">Optional parameter: The priority of the notification. Can be: `low` or `high` and the default is `high`. A value of `low` optimizes the client app's battery consumption; however, notifications may be delivered with unspecified delay. For FCM and GCM, `low` priority is the same as `Normal` priority. For APNS `low` priority is the same as `5`. A value of `high` sends the notification immediately, and can wake up a sleeping device. For FCM and GCM, `high` is the same as `High` priority. For APNS, `high` is a priority `10`. SMS does not support this property..</param>
        /// <param name="ttl">Optional parameter: How long, in seconds, the notification is valid. Can be an integer between 0 and 2,419,200, which is 4 weeks, the default and the maximum supported time to live (TTL). Delivery should be attempted if the device is offline until the TTL elapses. Zero means that the notification delivery is attempted immediately, only once, and is not stored for future delivery. SMS does not support this property..</param>
        /// <param name="title">Optional parameter: The notification title. For FCM and GCM, this translates to the `data.twi_title` value. For APNS, this translates to the `aps.alert.title` value. SMS does not support this property. This field is not visible on iOS phones and tablets but appears on Apple Watch and Android devices..</param>
        /// <param name="sound">Optional parameter: The name of the sound to be played for the notification. For FCM and GCM, this Translates to `data.twi_sound`.  For APNS, this translates to `aps.sound`.  SMS does not support this property..</param>
        /// <param name="action">Optional parameter: The actions to display for the notification. For APNS, translates to the `aps.category` value. For GCM, translates to the `data.twi_action` value. For SMS, this parameter is not supported and is omitted from deliveries to those channels..</param>
        /// <param name="data">Optional parameter: The custom key-value pairs of the notification's payload. For FCM and GCM, this value translates to `data` in the FCM and GCM payloads. FCM and GCM [reserve certain keys](https://firebase.google.com/docs/cloud-messaging/http-server-ref) that cannot be used in those channels. For APNS, attributes of `data` are inserted into the APNS payload as custom properties outside of the `aps` dictionary. In all channels, we reserve keys that start with `twi_` for future use. Custom keys that start with `twi_` are not allowed and are rejected as 400 Bad request with no delivery attempted. For SMS, this parameter is not supported and is omitted from deliveries to those channels..</param>
        /// <param name="apn">Optional parameter: The APNS-specific payload that overrides corresponding attributes in the generic payload for APNS Bindings. This property maps to the APNS `Payload` item, therefore the `aps` key must be used to change standard attributes. Adds custom key-value pairs to the root of the dictionary. See the [APNS documentation](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html) for more details. We reserve keys that start with `twi_` for future use. Custom keys that start with `twi_` are not allowed..</param>
        /// <param name="gcm">Optional parameter: The GCM-specific payload that overrides corresponding attributes in the generic payload for GCM Bindings.  This property maps to the root JSON dictionary. See the [GCM documentation](https://firebase.google.com/docs/cloud-messaging/http-server-ref) for more details. Target parameters `to`, `registration_ids`, and `notification_key` are not allowed. We reserve keys that start with `twi_` for future use. Custom keys that start with `twi_` are not allowed. GCM also [reserves certain keys](https://firebase.google.com/docs/cloud-messaging/http-server-ref)..</param>
        /// <param name="sms">Optional parameter: The SMS-specific payload that overrides corresponding attributes in the generic payload for SMS Bindings.  Each attribute in this value maps to the corresponding `form` parameter of the Twilio [Message](https://www.twilio.com/docs/sms/quickstart) resource.  These parameters of the Message resource are supported in snake case format: `body`, `media_urls`, `status_callback`, and `max_price`.  The `status_callback` parameter overrides the corresponding parameter in the messaging service, if configured. The `media_urls` property expects a JSON array..</param>
        /// <param name="facebookMessenger">Optional parameter: Deprecated..</param>
        /// <param name="fcm">Optional parameter: The FCM-specific payload that overrides corresponding attributes in the generic payload for FCM Bindings. This property maps to the root JSON dictionary. See the [FCM documentation](https://firebase.google.com/docs/cloud-messaging/http-server-ref#downstream) for more details. Target parameters `to`, `registration_ids`, `condition`, and `notification_key` are not allowed in this parameter. We reserve keys that start with `twi_` for future use. Custom keys that start with `twi_` are not allowed. FCM also [reserves certain keys](https://firebase.google.com/docs/cloud-messaging/http-server-ref), which cannot be used in that channel..</param>
        /// <param name="segment">Optional parameter: The Segment resource is deprecated. Use the `tag` parameter, instead..</param>
        /// <param name="alexa">Optional parameter: Deprecated..</param>
        /// <param name="toBinding">Optional parameter: The destination address specified as a JSON string.  Multiple `to_binding` parameters can be included but the total size of the request entity should not exceed 1MB. This is typically sufficient for 10,000 phone numbers..</param>
        /// <param name="deliveryCallbackUrl">Optional parameter: URL to send webhooks..</param>
        /// <param name="identity">Optional parameter: The `identity` value that uniquely identifies the new resource's [User](https://www.twilio.com/docs/chat/rest/user-resource) within the [Service](https://www.twilio.com/docs/notify/api/service-resource). Delivery will be attempted only to Bindings with an Identity in this list. No more than 20 items are allowed in this list..</param>
        /// <param name="tag">Optional parameter: A tag that selects the Bindings to notify. Repeat this parameter to specify more than one tag, up to a total of 5 tags. The implicit tag `all` is available to notify all Bindings in a Service instance. Similarly, the implicit tags `apn`, `fcm`, `gcm`, `sms` and `facebook-messenger` are available to notify all Bindings in a specific channel..</param>
        /// <returns>Returns the ApiResponse of Models.Notification response from the API call.</returns>
        public ApiResponse<Models.Notification> CreateNotification(
                string serviceSid,
                string body = null,
                Models.NotifPriority? priority = null,
                int? ttl = null,
                string title = null,
                string sound = null,
                string action = null,
                object data = null,
                object apn = null,
                object gcm = null,
                object sms = null,
                object facebookMessenger = null,
                object fcm = null,
                List<string> segment = null,
                object alexa = null,
                List<string> toBinding = null,
                string deliveryCallbackUrl = null,
                List<string> identity = null,
                List<string> tag = null)
            => CoreHelper.RunTask(CreateNotificationAsync(serviceSid, body, priority, ttl, title, sound, action, data, apn, gcm, sms, facebookMessenger, fcm, segment, alexa, toBinding, deliveryCallbackUrl, identity, tag));

        /// <summary>
        /// CreateNotification EndPoint.
        /// </summary>
        /// <param name="serviceSid">Required parameter: The SID of the [Service](https://www.twilio.com/docs/notify/api/service-resource) to create the resource under..</param>
        /// <param name="body">Optional parameter: The notification text. For FCM and GCM, translates to `data.twi_body`. For APNS, translates to `aps.alert.body`. For SMS, translates to `body`. SMS requires either this `body` value, or `media_urls` attribute defined in the `sms` parameter of the notification..</param>
        /// <param name="priority">Optional parameter: The priority of the notification. Can be: `low` or `high` and the default is `high`. A value of `low` optimizes the client app's battery consumption; however, notifications may be delivered with unspecified delay. For FCM and GCM, `low` priority is the same as `Normal` priority. For APNS `low` priority is the same as `5`. A value of `high` sends the notification immediately, and can wake up a sleeping device. For FCM and GCM, `high` is the same as `High` priority. For APNS, `high` is a priority `10`. SMS does not support this property..</param>
        /// <param name="ttl">Optional parameter: How long, in seconds, the notification is valid. Can be an integer between 0 and 2,419,200, which is 4 weeks, the default and the maximum supported time to live (TTL). Delivery should be attempted if the device is offline until the TTL elapses. Zero means that the notification delivery is attempted immediately, only once, and is not stored for future delivery. SMS does not support this property..</param>
        /// <param name="title">Optional parameter: The notification title. For FCM and GCM, this translates to the `data.twi_title` value. For APNS, this translates to the `aps.alert.title` value. SMS does not support this property. This field is not visible on iOS phones and tablets but appears on Apple Watch and Android devices..</param>
        /// <param name="sound">Optional parameter: The name of the sound to be played for the notification. For FCM and GCM, this Translates to `data.twi_sound`.  For APNS, this translates to `aps.sound`.  SMS does not support this property..</param>
        /// <param name="action">Optional parameter: The actions to display for the notification. For APNS, translates to the `aps.category` value. For GCM, translates to the `data.twi_action` value. For SMS, this parameter is not supported and is omitted from deliveries to those channels..</param>
        /// <param name="data">Optional parameter: The custom key-value pairs of the notification's payload. For FCM and GCM, this value translates to `data` in the FCM and GCM payloads. FCM and GCM [reserve certain keys](https://firebase.google.com/docs/cloud-messaging/http-server-ref) that cannot be used in those channels. For APNS, attributes of `data` are inserted into the APNS payload as custom properties outside of the `aps` dictionary. In all channels, we reserve keys that start with `twi_` for future use. Custom keys that start with `twi_` are not allowed and are rejected as 400 Bad request with no delivery attempted. For SMS, this parameter is not supported and is omitted from deliveries to those channels..</param>
        /// <param name="apn">Optional parameter: The APNS-specific payload that overrides corresponding attributes in the generic payload for APNS Bindings. This property maps to the APNS `Payload` item, therefore the `aps` key must be used to change standard attributes. Adds custom key-value pairs to the root of the dictionary. See the [APNS documentation](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html) for more details. We reserve keys that start with `twi_` for future use. Custom keys that start with `twi_` are not allowed..</param>
        /// <param name="gcm">Optional parameter: The GCM-specific payload that overrides corresponding attributes in the generic payload for GCM Bindings.  This property maps to the root JSON dictionary. See the [GCM documentation](https://firebase.google.com/docs/cloud-messaging/http-server-ref) for more details. Target parameters `to`, `registration_ids`, and `notification_key` are not allowed. We reserve keys that start with `twi_` for future use. Custom keys that start with `twi_` are not allowed. GCM also [reserves certain keys](https://firebase.google.com/docs/cloud-messaging/http-server-ref)..</param>
        /// <param name="sms">Optional parameter: The SMS-specific payload that overrides corresponding attributes in the generic payload for SMS Bindings.  Each attribute in this value maps to the corresponding `form` parameter of the Twilio [Message](https://www.twilio.com/docs/sms/quickstart) resource.  These parameters of the Message resource are supported in snake case format: `body`, `media_urls`, `status_callback`, and `max_price`.  The `status_callback` parameter overrides the corresponding parameter in the messaging service, if configured. The `media_urls` property expects a JSON array..</param>
        /// <param name="facebookMessenger">Optional parameter: Deprecated..</param>
        /// <param name="fcm">Optional parameter: The FCM-specific payload that overrides corresponding attributes in the generic payload for FCM Bindings. This property maps to the root JSON dictionary. See the [FCM documentation](https://firebase.google.com/docs/cloud-messaging/http-server-ref#downstream) for more details. Target parameters `to`, `registration_ids`, `condition`, and `notification_key` are not allowed in this parameter. We reserve keys that start with `twi_` for future use. Custom keys that start with `twi_` are not allowed. FCM also [reserves certain keys](https://firebase.google.com/docs/cloud-messaging/http-server-ref), which cannot be used in that channel..</param>
        /// <param name="segment">Optional parameter: The Segment resource is deprecated. Use the `tag` parameter, instead..</param>
        /// <param name="alexa">Optional parameter: Deprecated..</param>
        /// <param name="toBinding">Optional parameter: The destination address specified as a JSON string.  Multiple `to_binding` parameters can be included but the total size of the request entity should not exceed 1MB. This is typically sufficient for 10,000 phone numbers..</param>
        /// <param name="deliveryCallbackUrl">Optional parameter: URL to send webhooks..</param>
        /// <param name="identity">Optional parameter: The `identity` value that uniquely identifies the new resource's [User](https://www.twilio.com/docs/chat/rest/user-resource) within the [Service](https://www.twilio.com/docs/notify/api/service-resource). Delivery will be attempted only to Bindings with an Identity in this list. No more than 20 items are allowed in this list..</param>
        /// <param name="tag">Optional parameter: A tag that selects the Bindings to notify. Repeat this parameter to specify more than one tag, up to a total of 5 tags. The implicit tag `all` is available to notify all Bindings in a Service instance. Similarly, the implicit tags `apn`, `fcm`, `gcm`, `sms` and `facebook-messenger` are available to notify all Bindings in a specific channel..</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.Notification response from the API call.</returns>
        public async Task<ApiResponse<Models.Notification>> CreateNotificationAsync(
                string serviceSid,
                string body = null,
                Models.NotifPriority? priority = null,
                int? ttl = null,
                string title = null,
                string sound = null,
                string action = null,
                object data = null,
                object apn = null,
                object gcm = null,
                object sms = null,
                object facebookMessenger = null,
                object fcm = null,
                List<string> segment = null,
                object alexa = null,
                List<string> toBinding = null,
                string deliveryCallbackUrl = null,
                List<string> identity = null,
                List<string> tag = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.Notification>()
              .Server(Server.Default3)
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Post, "/v1/Services/{ServiceSid}/Notifications")
                  .WithAuth("accountSid_authToken")
                  .Parameters(parameters => parameters
                      .Template(template => template.Setup("ServiceSid", serviceSid).Required())
                      .Header(header => header.Setup("Content-Type", "application/x-www-form-urlencoded"))
                      .Form(form => form.Setup("Body", body))
                      .Form(form => form.Setup("Priority", (priority.HasValue) ? CoreHelper.JsonSerialize(priority.Value).Trim('\"') : null))
                      .Form(form => form.Setup("Ttl", ttl))
                      .Form(form => form.Setup("Title", title))
                      .Form(form => form.Setup("Sound", sound))
                      .Form(form => form.Setup("Action", action))
                      .Form(form => form.Setup("Data", data))
                      .Form(form => form.Setup("Apn", apn))
                      .Form(form => form.Setup("Gcm", gcm))
                      .Form(form => form.Setup("Sms", sms))
                      .Form(form => form.Setup("FacebookMessenger", facebookMessenger))
                      .Form(form => form.Setup("Fcm", fcm))
                      .Form(form => form.Setup("Segment", segment))
                      .Form(form => form.Setup("Alexa", alexa))
                      .Form(form => form.Setup("ToBinding", toBinding))
                      .Form(form => form.Setup("DeliveryCallbackUrl", deliveryCallbackUrl))
                      .Form(form => form.Setup("Identity", identity))
                      .Form(form => form.Setup("Tag", tag))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);
    }
}