// <copyright file="NotifyV1ServiceApi.cs" company="APIMatic">
// TwilioApIs.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core;
using APIMatic.Core.Types;
using APIMatic.Core.Utilities;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using TwilioApIs.Standard.Http.Response;

namespace TwilioApIs.Standard.Apis
{
    /// <summary>
    /// NotifyV1ServiceApi.
    /// </summary>
    public class NotifyV1ServiceApi : BaseApi
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NotifyV1ServiceApi"/> class.
        /// </summary>
        internal NotifyV1ServiceApi(GlobalConfiguration globalConfiguration) : base(globalConfiguration) { }

        /// <summary>
        /// CreateService EndPoint.
        /// </summary>
        /// <param name="friendlyName">Optional parameter: A descriptive string that you create to describe the resource. It can be up to 64 characters long..</param>
        /// <param name="apnCredentialSid">Optional parameter: The SID of the [Credential](https://www.twilio.com/docs/notify/api/credential-resource) to use for APN Bindings..</param>
        /// <param name="gcmCredentialSid">Optional parameter: The SID of the [Credential](https://www.twilio.com/docs/notify/api/credential-resource) to use for GCM Bindings..</param>
        /// <param name="messagingServiceSid">Optional parameter: The SID of the [Messaging Service](https://www.twilio.com/docs/sms/quickstart#messaging-services) to use for SMS Bindings. This parameter must be set in order to send SMS notifications..</param>
        /// <param name="facebookMessengerPageId">Optional parameter: Deprecated..</param>
        /// <param name="defaultApnNotificationProtocolVersion">Optional parameter: The protocol version to use for sending APNS notifications. Can be overridden on a Binding by Binding basis when creating a [Binding](https://www.twilio.com/docs/notify/api/binding-resource) resource..</param>
        /// <param name="defaultGcmNotificationProtocolVersion">Optional parameter: The protocol version to use for sending GCM notifications. Can be overridden on a Binding by Binding basis when creating a [Binding](https://www.twilio.com/docs/notify/api/binding-resource) resource..</param>
        /// <param name="fcmCredentialSid">Optional parameter: The SID of the [Credential](https://www.twilio.com/docs/notify/api/credential-resource) to use for FCM Bindings..</param>
        /// <param name="defaultFcmNotificationProtocolVersion">Optional parameter: The protocol version to use for sending FCM notifications. Can be overridden on a Binding by Binding basis when creating a [Binding](https://www.twilio.com/docs/notify/api/binding-resource) resource..</param>
        /// <param name="logEnabled">Optional parameter: Whether to log notifications. Can be: `true` or `false` and the default is `true`..</param>
        /// <param name="alexaSkillId">Optional parameter: Deprecated..</param>
        /// <param name="defaultAlexaNotificationProtocolVersion">Optional parameter: Deprecated..</param>
        /// <param name="deliveryCallbackUrl">Optional parameter: URL to send delivery status callback..</param>
        /// <param name="deliveryCallbackEnabled">Optional parameter: Callback configuration that enables delivery callbacks, default false.</param>
        /// <returns>Returns the ApiResponse of Models.Service1 response from the API call.</returns>
        public ApiResponse<Models.Service1> CreateService(
                string friendlyName = null,
                string apnCredentialSid = null,
                string gcmCredentialSid = null,
                string messagingServiceSid = null,
                string facebookMessengerPageId = null,
                string defaultApnNotificationProtocolVersion = null,
                string defaultGcmNotificationProtocolVersion = null,
                string fcmCredentialSid = null,
                string defaultFcmNotificationProtocolVersion = null,
                bool? logEnabled = null,
                string alexaSkillId = null,
                string defaultAlexaNotificationProtocolVersion = null,
                string deliveryCallbackUrl = null,
                bool? deliveryCallbackEnabled = null)
            => CoreHelper.RunTask(CreateServiceAsync(friendlyName, apnCredentialSid, gcmCredentialSid, messagingServiceSid, facebookMessengerPageId, defaultApnNotificationProtocolVersion, defaultGcmNotificationProtocolVersion, fcmCredentialSid, defaultFcmNotificationProtocolVersion, logEnabled, alexaSkillId, defaultAlexaNotificationProtocolVersion, deliveryCallbackUrl, deliveryCallbackEnabled));

        /// <summary>
        /// CreateService EndPoint.
        /// </summary>
        /// <param name="friendlyName">Optional parameter: A descriptive string that you create to describe the resource. It can be up to 64 characters long..</param>
        /// <param name="apnCredentialSid">Optional parameter: The SID of the [Credential](https://www.twilio.com/docs/notify/api/credential-resource) to use for APN Bindings..</param>
        /// <param name="gcmCredentialSid">Optional parameter: The SID of the [Credential](https://www.twilio.com/docs/notify/api/credential-resource) to use for GCM Bindings..</param>
        /// <param name="messagingServiceSid">Optional parameter: The SID of the [Messaging Service](https://www.twilio.com/docs/sms/quickstart#messaging-services) to use for SMS Bindings. This parameter must be set in order to send SMS notifications..</param>
        /// <param name="facebookMessengerPageId">Optional parameter: Deprecated..</param>
        /// <param name="defaultApnNotificationProtocolVersion">Optional parameter: The protocol version to use for sending APNS notifications. Can be overridden on a Binding by Binding basis when creating a [Binding](https://www.twilio.com/docs/notify/api/binding-resource) resource..</param>
        /// <param name="defaultGcmNotificationProtocolVersion">Optional parameter: The protocol version to use for sending GCM notifications. Can be overridden on a Binding by Binding basis when creating a [Binding](https://www.twilio.com/docs/notify/api/binding-resource) resource..</param>
        /// <param name="fcmCredentialSid">Optional parameter: The SID of the [Credential](https://www.twilio.com/docs/notify/api/credential-resource) to use for FCM Bindings..</param>
        /// <param name="defaultFcmNotificationProtocolVersion">Optional parameter: The protocol version to use for sending FCM notifications. Can be overridden on a Binding by Binding basis when creating a [Binding](https://www.twilio.com/docs/notify/api/binding-resource) resource..</param>
        /// <param name="logEnabled">Optional parameter: Whether to log notifications. Can be: `true` or `false` and the default is `true`..</param>
        /// <param name="alexaSkillId">Optional parameter: Deprecated..</param>
        /// <param name="defaultAlexaNotificationProtocolVersion">Optional parameter: Deprecated..</param>
        /// <param name="deliveryCallbackUrl">Optional parameter: URL to send delivery status callback..</param>
        /// <param name="deliveryCallbackEnabled">Optional parameter: Callback configuration that enables delivery callbacks, default false.</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.Service1 response from the API call.</returns>
        public async Task<ApiResponse<Models.Service1>> CreateServiceAsync(
                string friendlyName = null,
                string apnCredentialSid = null,
                string gcmCredentialSid = null,
                string messagingServiceSid = null,
                string facebookMessengerPageId = null,
                string defaultApnNotificationProtocolVersion = null,
                string defaultGcmNotificationProtocolVersion = null,
                string fcmCredentialSid = null,
                string defaultFcmNotificationProtocolVersion = null,
                bool? logEnabled = null,
                string alexaSkillId = null,
                string defaultAlexaNotificationProtocolVersion = null,
                string deliveryCallbackUrl = null,
                bool? deliveryCallbackEnabled = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.Service1>()
              .Server(Server.Default3)
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Post, "/v1/Services")
                  .WithAuth("accountSid_authToken")
                  .Parameters(parameters => parameters
                      .Header(header => header.Setup("Content-Type", "application/x-www-form-urlencoded"))
                      .Form(form => form.Setup("FriendlyName", friendlyName))
                      .Form(form => form.Setup("ApnCredentialSid", apnCredentialSid))
                      .Form(form => form.Setup("GcmCredentialSid", gcmCredentialSid))
                      .Form(form => form.Setup("MessagingServiceSid", messagingServiceSid))
                      .Form(form => form.Setup("FacebookMessengerPageId", facebookMessengerPageId))
                      .Form(form => form.Setup("DefaultApnNotificationProtocolVersion", defaultApnNotificationProtocolVersion))
                      .Form(form => form.Setup("DefaultGcmNotificationProtocolVersion", defaultGcmNotificationProtocolVersion))
                      .Form(form => form.Setup("FcmCredentialSid", fcmCredentialSid))
                      .Form(form => form.Setup("DefaultFcmNotificationProtocolVersion", defaultFcmNotificationProtocolVersion))
                      .Form(form => form.Setup("LogEnabled", logEnabled))
                      .Form(form => form.Setup("AlexaSkillId", alexaSkillId))
                      .Form(form => form.Setup("DefaultAlexaNotificationProtocolVersion", defaultAlexaNotificationProtocolVersion))
                      .Form(form => form.Setup("DeliveryCallbackUrl", deliveryCallbackUrl))
                      .Form(form => form.Setup("DeliveryCallbackEnabled", deliveryCallbackEnabled))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// ListService EndPoint.
        /// </summary>
        /// <param name="friendlyName">Optional parameter: The string that identifies the Service resources to read..</param>
        /// <param name="pageSize">Optional parameter: How many resources to return in each list page. The default is 50, and the maximum is 1000..</param>
        /// <param name="page">Optional parameter: The page index. This value is simply for client state..</param>
        /// <param name="pageToken">Optional parameter: The page token. This is provided by the API..</param>
        /// <returns>Returns the ApiResponse of Models.ListServiceResponse response from the API call.</returns>
        public ApiResponse<Models.ListServiceResponse> ListService(
                string friendlyName = null,
                long? pageSize = null,
                int? page = null,
                string pageToken = null)
            => CoreHelper.RunTask(ListServiceAsync(friendlyName, pageSize, page, pageToken));

        /// <summary>
        /// ListService EndPoint.
        /// </summary>
        /// <param name="friendlyName">Optional parameter: The string that identifies the Service resources to read..</param>
        /// <param name="pageSize">Optional parameter: How many resources to return in each list page. The default is 50, and the maximum is 1000..</param>
        /// <param name="page">Optional parameter: The page index. This value is simply for client state..</param>
        /// <param name="pageToken">Optional parameter: The page token. This is provided by the API..</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.ListServiceResponse response from the API call.</returns>
        public async Task<ApiResponse<Models.ListServiceResponse>> ListServiceAsync(
                string friendlyName = null,
                long? pageSize = null,
                int? page = null,
                string pageToken = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.ListServiceResponse>()
              .Server(Server.Default3)
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Get, "/v1/Services")
                  .WithAuth("accountSid_authToken")
                  .Parameters(parameters => parameters
                      .Query(query => query.Setup("FriendlyName", friendlyName))
                      .Query(query => query.Setup("PageSize", pageSize))
                      .Query(query => query.Setup("Page", page))
                      .Query(query => query.Setup("PageToken", pageToken))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// DeleteService EndPoint.
        /// </summary>
        /// <param name="sid">Required parameter: The Twilio-provided string that uniquely identifies the Service resource to delete..</param>
        public void DeleteService(
                string sid)
            => CoreHelper.RunVoidTask(DeleteServiceAsync(sid));

        /// <summary>
        /// DeleteService EndPoint.
        /// </summary>
        /// <param name="sid">Required parameter: The Twilio-provided string that uniquely identifies the Service resource to delete..</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the void response from the API call.</returns>
        public async Task DeleteServiceAsync(
                string sid,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<VoidType>()
              .Server(Server.Default3)
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Delete, "/v1/Services/{Sid}")
                  .WithAuth("accountSid_authToken")
                  .Parameters(parameters => parameters
                      .Template(template => template.Setup("Sid", sid).Required())))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// FetchService EndPoint.
        /// </summary>
        /// <param name="sid">Required parameter: The Twilio-provided string that uniquely identifies the Service resource to fetch..</param>
        /// <returns>Returns the ApiResponse of Models.Service1 response from the API call.</returns>
        public ApiResponse<Models.Service1> FetchService(
                string sid)
            => CoreHelper.RunTask(FetchServiceAsync(sid));

        /// <summary>
        /// FetchService EndPoint.
        /// </summary>
        /// <param name="sid">Required parameter: The Twilio-provided string that uniquely identifies the Service resource to fetch..</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.Service1 response from the API call.</returns>
        public async Task<ApiResponse<Models.Service1>> FetchServiceAsync(
                string sid,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.Service1>()
              .Server(Server.Default3)
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Get, "/v1/Services/{Sid}")
                  .WithAuth("accountSid_authToken")
                  .Parameters(parameters => parameters
                      .Template(template => template.Setup("Sid", sid).Required())))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// UpdateService EndPoint.
        /// </summary>
        /// <param name="sid">Required parameter: The Twilio-provided string that uniquely identifies the Service resource to update..</param>
        /// <param name="friendlyName">Optional parameter: A descriptive string that you create to describe the resource. It can be up to 64 characters long..</param>
        /// <param name="apnCredentialSid">Optional parameter: The SID of the [Credential](https://www.twilio.com/docs/notify/api/credential-resource) to use for APN Bindings..</param>
        /// <param name="gcmCredentialSid">Optional parameter: The SID of the [Credential](https://www.twilio.com/docs/notify/api/credential-resource) to use for GCM Bindings..</param>
        /// <param name="messagingServiceSid">Optional parameter: The SID of the [Messaging Service](https://www.twilio.com/docs/sms/quickstart#messaging-services) to use for SMS Bindings. This parameter must be set in order to send SMS notifications..</param>
        /// <param name="facebookMessengerPageId">Optional parameter: Deprecated..</param>
        /// <param name="defaultApnNotificationProtocolVersion">Optional parameter: The protocol version to use for sending APNS notifications. Can be overridden on a Binding by Binding basis when creating a [Binding](https://www.twilio.com/docs/notify/api/binding-resource) resource..</param>
        /// <param name="defaultGcmNotificationProtocolVersion">Optional parameter: The protocol version to use for sending GCM notifications. Can be overridden on a Binding by Binding basis when creating a [Binding](https://www.twilio.com/docs/notify/api/binding-resource) resource..</param>
        /// <param name="fcmCredentialSid">Optional parameter: The SID of the [Credential](https://www.twilio.com/docs/notify/api/credential-resource) to use for FCM Bindings..</param>
        /// <param name="defaultFcmNotificationProtocolVersion">Optional parameter: The protocol version to use for sending FCM notifications. Can be overridden on a Binding by Binding basis when creating a [Binding](https://www.twilio.com/docs/notify/api/binding-resource) resource..</param>
        /// <param name="logEnabled">Optional parameter: Whether to log notifications. Can be: `true` or `false` and the default is `true`..</param>
        /// <param name="alexaSkillId">Optional parameter: Deprecated..</param>
        /// <param name="defaultAlexaNotificationProtocolVersion">Optional parameter: Deprecated..</param>
        /// <param name="deliveryCallbackUrl">Optional parameter: URL to send delivery status callback..</param>
        /// <param name="deliveryCallbackEnabled">Optional parameter: Callback configuration that enables delivery callbacks, default false.</param>
        /// <returns>Returns the ApiResponse of Models.Service1 response from the API call.</returns>
        public ApiResponse<Models.Service1> UpdateService(
                string sid,
                string friendlyName = null,
                string apnCredentialSid = null,
                string gcmCredentialSid = null,
                string messagingServiceSid = null,
                string facebookMessengerPageId = null,
                string defaultApnNotificationProtocolVersion = null,
                string defaultGcmNotificationProtocolVersion = null,
                string fcmCredentialSid = null,
                string defaultFcmNotificationProtocolVersion = null,
                bool? logEnabled = null,
                string alexaSkillId = null,
                string defaultAlexaNotificationProtocolVersion = null,
                string deliveryCallbackUrl = null,
                bool? deliveryCallbackEnabled = null)
            => CoreHelper.RunTask(UpdateServiceAsync(sid, friendlyName, apnCredentialSid, gcmCredentialSid, messagingServiceSid, facebookMessengerPageId, defaultApnNotificationProtocolVersion, defaultGcmNotificationProtocolVersion, fcmCredentialSid, defaultFcmNotificationProtocolVersion, logEnabled, alexaSkillId, defaultAlexaNotificationProtocolVersion, deliveryCallbackUrl, deliveryCallbackEnabled));

        /// <summary>
        /// UpdateService EndPoint.
        /// </summary>
        /// <param name="sid">Required parameter: The Twilio-provided string that uniquely identifies the Service resource to update..</param>
        /// <param name="friendlyName">Optional parameter: A descriptive string that you create to describe the resource. It can be up to 64 characters long..</param>
        /// <param name="apnCredentialSid">Optional parameter: The SID of the [Credential](https://www.twilio.com/docs/notify/api/credential-resource) to use for APN Bindings..</param>
        /// <param name="gcmCredentialSid">Optional parameter: The SID of the [Credential](https://www.twilio.com/docs/notify/api/credential-resource) to use for GCM Bindings..</param>
        /// <param name="messagingServiceSid">Optional parameter: The SID of the [Messaging Service](https://www.twilio.com/docs/sms/quickstart#messaging-services) to use for SMS Bindings. This parameter must be set in order to send SMS notifications..</param>
        /// <param name="facebookMessengerPageId">Optional parameter: Deprecated..</param>
        /// <param name="defaultApnNotificationProtocolVersion">Optional parameter: The protocol version to use for sending APNS notifications. Can be overridden on a Binding by Binding basis when creating a [Binding](https://www.twilio.com/docs/notify/api/binding-resource) resource..</param>
        /// <param name="defaultGcmNotificationProtocolVersion">Optional parameter: The protocol version to use for sending GCM notifications. Can be overridden on a Binding by Binding basis when creating a [Binding](https://www.twilio.com/docs/notify/api/binding-resource) resource..</param>
        /// <param name="fcmCredentialSid">Optional parameter: The SID of the [Credential](https://www.twilio.com/docs/notify/api/credential-resource) to use for FCM Bindings..</param>
        /// <param name="defaultFcmNotificationProtocolVersion">Optional parameter: The protocol version to use for sending FCM notifications. Can be overridden on a Binding by Binding basis when creating a [Binding](https://www.twilio.com/docs/notify/api/binding-resource) resource..</param>
        /// <param name="logEnabled">Optional parameter: Whether to log notifications. Can be: `true` or `false` and the default is `true`..</param>
        /// <param name="alexaSkillId">Optional parameter: Deprecated..</param>
        /// <param name="defaultAlexaNotificationProtocolVersion">Optional parameter: Deprecated..</param>
        /// <param name="deliveryCallbackUrl">Optional parameter: URL to send delivery status callback..</param>
        /// <param name="deliveryCallbackEnabled">Optional parameter: Callback configuration that enables delivery callbacks, default false.</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.Service1 response from the API call.</returns>
        public async Task<ApiResponse<Models.Service1>> UpdateServiceAsync(
                string sid,
                string friendlyName = null,
                string apnCredentialSid = null,
                string gcmCredentialSid = null,
                string messagingServiceSid = null,
                string facebookMessengerPageId = null,
                string defaultApnNotificationProtocolVersion = null,
                string defaultGcmNotificationProtocolVersion = null,
                string fcmCredentialSid = null,
                string defaultFcmNotificationProtocolVersion = null,
                bool? logEnabled = null,
                string alexaSkillId = null,
                string defaultAlexaNotificationProtocolVersion = null,
                string deliveryCallbackUrl = null,
                bool? deliveryCallbackEnabled = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.Service1>()
              .Server(Server.Default3)
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Post, "/v1/Services/{Sid}")
                  .WithAuth("accountSid_authToken")
                  .Parameters(parameters => parameters
                      .Template(template => template.Setup("Sid", sid).Required())
                      .Header(header => header.Setup("Content-Type", "application/x-www-form-urlencoded"))
                      .Form(form => form.Setup("FriendlyName", friendlyName))
                      .Form(form => form.Setup("ApnCredentialSid", apnCredentialSid))
                      .Form(form => form.Setup("GcmCredentialSid", gcmCredentialSid))
                      .Form(form => form.Setup("MessagingServiceSid", messagingServiceSid))
                      .Form(form => form.Setup("FacebookMessengerPageId", facebookMessengerPageId))
                      .Form(form => form.Setup("DefaultApnNotificationProtocolVersion", defaultApnNotificationProtocolVersion))
                      .Form(form => form.Setup("DefaultGcmNotificationProtocolVersion", defaultGcmNotificationProtocolVersion))
                      .Form(form => form.Setup("FcmCredentialSid", fcmCredentialSid))
                      .Form(form => form.Setup("DefaultFcmNotificationProtocolVersion", defaultFcmNotificationProtocolVersion))
                      .Form(form => form.Setup("LogEnabled", logEnabled))
                      .Form(form => form.Setup("AlexaSkillId", alexaSkillId))
                      .Form(form => form.Setup("DefaultAlexaNotificationProtocolVersion", defaultAlexaNotificationProtocolVersion))
                      .Form(form => form.Setup("DeliveryCallbackUrl", deliveryCallbackUrl))
                      .Form(form => form.Setup("DeliveryCallbackEnabled", deliveryCallbackEnabled))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);
    }
}