// <copyright file="VerifyV2ServiceApi.cs" company="APIMatic">
// TwilioApIs.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core;
using APIMatic.Core.Utilities;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using TwilioApIs.Standard.Http.Response;

namespace TwilioApIs.Standard.Apis
{
    /// <summary>
    /// VerifyV2ServiceApi.
    /// </summary>
    public class VerifyV2ServiceApi : BaseApi
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VerifyV2ServiceApi"/> class.
        /// </summary>
        internal VerifyV2ServiceApi(GlobalConfiguration globalConfiguration) : base(globalConfiguration) { }

        /// <summary>
        /// Create a new Verification Service.
        /// </summary>
        /// <param name="friendlyName">Required parameter: A descriptive string that you create to describe the verification service. It can be up to 32 characters long. **This value should not contain PII.**.</param>
        /// <param name="codeLength">Optional parameter: The length of the verification code to generate. Must be an integer value between 4 and 10, inclusive..</param>
        /// <param name="lookupEnabled">Optional parameter: Whether to perform a lookup with each verification started and return info about the phone number..</param>
        /// <param name="skipSmsToLandlines">Optional parameter: Whether to skip sending SMS verifications to landlines. Requires `lookup_enabled`..</param>
        /// <param name="dtmfInputRequired">Optional parameter: Whether to ask the user to press a number before delivering the verify code in a phone call..</param>
        /// <param name="ttsName">Optional parameter: The name of an alternative text-to-speech service to use in phone calls. Applies only to TTS languages..</param>
        /// <param name="psd2Enabled">Optional parameter: Whether to pass PSD2 transaction parameters when starting a verification..</param>
        /// <param name="doNotShareWarningEnabled">Optional parameter: Whether to add a security warning at the end of an SMS verification body. Disabled by default and applies only to SMS. Example SMS body: `Your AppName verification code is: 1234. Don’t share this code with anyone; our employees will never ask for the code`.</param>
        /// <param name="customCodeEnabled">Optional parameter: Whether to allow sending verifications with a custom code instead of a randomly generated one..</param>
        /// <param name="pushIncludeDate">Optional parameter: Optional configuration for the Push factors. If true, include the date in the Challenge's response. Otherwise, the date is omitted from the response. See [Challenge](https://www.twilio.com/docs/verify/api/challenge) resource’s details parameter for more info. Default: false. **Deprecated** do not use this parameter. This timestamp value is the same one as the one found in `date_created`, please use that one instead..</param>
        /// <param name="pushApnCredentialSid">Optional parameter: Optional configuration for the Push factors. Set the APN Credential for this service. This will allow to send push notifications to iOS devices. See [Credential Resource](https://www.twilio.com/docs/notify/api/credential-resource).</param>
        /// <param name="pushFcmCredentialSid">Optional parameter: Optional configuration for the Push factors. Set the FCM Credential for this service. This will allow to send push notifications to Android devices. See [Credential Resource](https://www.twilio.com/docs/notify/api/credential-resource).</param>
        /// <param name="totpIssuer">Optional parameter: Optional configuration for the TOTP factors. Set TOTP Issuer for this service. This will allow to configure the issuer of the TOTP URI. Defaults to the service friendly name if not provided..</param>
        /// <param name="totpTimeStep">Optional parameter: Optional configuration for the TOTP factors. Defines how often, in seconds, are TOTP codes generated. i.e, a new TOTP code is generated every time_step seconds. Must be between 20 and 60 seconds, inclusive. Defaults to 30 seconds.</param>
        /// <param name="totpCodeLength">Optional parameter: Optional configuration for the TOTP factors. Number of digits for generated TOTP codes. Must be between 3 and 8, inclusive. Defaults to 6.</param>
        /// <param name="totpSkew">Optional parameter: Optional configuration for the TOTP factors. The number of time-steps, past and future, that are valid for validation of TOTP codes. Must be between 0 and 2, inclusive. Defaults to 1.</param>
        /// <param name="defaultTemplateSid">Optional parameter: The default message [template](https://www.twilio.com/docs/verify/api/templates). Will be used for all SMS verifications unless explicitly overriden. SMS channel only..</param>
        /// <param name="whatsappMsgServiceSid">Optional parameter: The SID of the Messaging Service containing WhatsApp Sender(s) that Verify will use to send WhatsApp messages to your users..</param>
        /// <param name="whatsappFrom">Optional parameter: The number to use as the WhatsApp Sender that Verify will use to send WhatsApp messages to your users.This WhatsApp Sender must be associated with a Messaging Service SID..</param>
        /// <param name="passkeysRelyingPartyId">Optional parameter: The Relying Party ID for Passkeys. This is the domain of your application, e.g. `example.com`. It is used to identify your application when creating Passkeys..</param>
        /// <param name="passkeysRelyingPartyName">Optional parameter: The Relying Party Name for Passkeys. This is the name of your application, e.g. `Example App`. It is used to identify your application when creating Passkeys..</param>
        /// <param name="passkeysRelyingPartyOrigins">Optional parameter: The Relying Party Origins for Passkeys. This is the origin of your application, e.g. `login.example.com,www.example.com`. It is used to identify your application when creating Passkeys, it can have multiple origins split by `,`..</param>
        /// <param name="passkeysAuthenticatorAttachment">Optional parameter: The Authenticator Attachment for Passkeys. This is the type of authenticator that will be used to create Passkeys. It can be empty or it can have the values `platform`, `cross-platform` or `any`..</param>
        /// <param name="passkeysDiscoverableCredentials">Optional parameter: Indicates whether credentials must be discoverable by the authenticator. It can be empty or it can have the values `required`, `preferred` or `discouraged`..</param>
        /// <param name="passkeysUserVerification">Optional parameter: The User Verification for Passkeys. This is the type of user verification that will be used to create Passkeys. It can be empty or it can have the values `required`, `preferred` or `discouraged`..</param>
        /// <param name="verifyEventSubscriptionEnabled">Optional parameter: Whether to allow verifications from the service to reach the stream-events sinks if configured.</param>
        /// <returns>Returns the ApiResponse of Models.Service2 response from the API call.</returns>
        public ApiResponse<Models.Service2> CreateService(
                string friendlyName,
                int? codeLength = null,
                bool? lookupEnabled = null,
                bool? skipSmsToLandlines = null,
                bool? dtmfInputRequired = null,
                string ttsName = null,
                bool? psd2Enabled = null,
                bool? doNotShareWarningEnabled = null,
                bool? customCodeEnabled = null,
                bool? pushIncludeDate = null,
                string pushApnCredentialSid = null,
                string pushFcmCredentialSid = null,
                string totpIssuer = null,
                int? totpTimeStep = null,
                int? totpCodeLength = null,
                int? totpSkew = null,
                string defaultTemplateSid = null,
                string whatsappMsgServiceSid = null,
                string whatsappFrom = null,
                string passkeysRelyingPartyId = null,
                string passkeysRelyingPartyName = null,
                string passkeysRelyingPartyOrigins = null,
                string passkeysAuthenticatorAttachment = null,
                string passkeysDiscoverableCredentials = null,
                string passkeysUserVerification = null,
                bool? verifyEventSubscriptionEnabled = null)
            => CoreHelper.RunTask(CreateServiceAsync(friendlyName, codeLength, lookupEnabled, skipSmsToLandlines, dtmfInputRequired, ttsName, psd2Enabled, doNotShareWarningEnabled, customCodeEnabled, pushIncludeDate, pushApnCredentialSid, pushFcmCredentialSid, totpIssuer, totpTimeStep, totpCodeLength, totpSkew, defaultTemplateSid, whatsappMsgServiceSid, whatsappFrom, passkeysRelyingPartyId, passkeysRelyingPartyName, passkeysRelyingPartyOrigins, passkeysAuthenticatorAttachment, passkeysDiscoverableCredentials, passkeysUserVerification, verifyEventSubscriptionEnabled));

        /// <summary>
        /// Create a new Verification Service.
        /// </summary>
        /// <param name="friendlyName">Required parameter: A descriptive string that you create to describe the verification service. It can be up to 32 characters long. **This value should not contain PII.**.</param>
        /// <param name="codeLength">Optional parameter: The length of the verification code to generate. Must be an integer value between 4 and 10, inclusive..</param>
        /// <param name="lookupEnabled">Optional parameter: Whether to perform a lookup with each verification started and return info about the phone number..</param>
        /// <param name="skipSmsToLandlines">Optional parameter: Whether to skip sending SMS verifications to landlines. Requires `lookup_enabled`..</param>
        /// <param name="dtmfInputRequired">Optional parameter: Whether to ask the user to press a number before delivering the verify code in a phone call..</param>
        /// <param name="ttsName">Optional parameter: The name of an alternative text-to-speech service to use in phone calls. Applies only to TTS languages..</param>
        /// <param name="psd2Enabled">Optional parameter: Whether to pass PSD2 transaction parameters when starting a verification..</param>
        /// <param name="doNotShareWarningEnabled">Optional parameter: Whether to add a security warning at the end of an SMS verification body. Disabled by default and applies only to SMS. Example SMS body: `Your AppName verification code is: 1234. Don’t share this code with anyone; our employees will never ask for the code`.</param>
        /// <param name="customCodeEnabled">Optional parameter: Whether to allow sending verifications with a custom code instead of a randomly generated one..</param>
        /// <param name="pushIncludeDate">Optional parameter: Optional configuration for the Push factors. If true, include the date in the Challenge's response. Otherwise, the date is omitted from the response. See [Challenge](https://www.twilio.com/docs/verify/api/challenge) resource’s details parameter for more info. Default: false. **Deprecated** do not use this parameter. This timestamp value is the same one as the one found in `date_created`, please use that one instead..</param>
        /// <param name="pushApnCredentialSid">Optional parameter: Optional configuration for the Push factors. Set the APN Credential for this service. This will allow to send push notifications to iOS devices. See [Credential Resource](https://www.twilio.com/docs/notify/api/credential-resource).</param>
        /// <param name="pushFcmCredentialSid">Optional parameter: Optional configuration for the Push factors. Set the FCM Credential for this service. This will allow to send push notifications to Android devices. See [Credential Resource](https://www.twilio.com/docs/notify/api/credential-resource).</param>
        /// <param name="totpIssuer">Optional parameter: Optional configuration for the TOTP factors. Set TOTP Issuer for this service. This will allow to configure the issuer of the TOTP URI. Defaults to the service friendly name if not provided..</param>
        /// <param name="totpTimeStep">Optional parameter: Optional configuration for the TOTP factors. Defines how often, in seconds, are TOTP codes generated. i.e, a new TOTP code is generated every time_step seconds. Must be between 20 and 60 seconds, inclusive. Defaults to 30 seconds.</param>
        /// <param name="totpCodeLength">Optional parameter: Optional configuration for the TOTP factors. Number of digits for generated TOTP codes. Must be between 3 and 8, inclusive. Defaults to 6.</param>
        /// <param name="totpSkew">Optional parameter: Optional configuration for the TOTP factors. The number of time-steps, past and future, that are valid for validation of TOTP codes. Must be between 0 and 2, inclusive. Defaults to 1.</param>
        /// <param name="defaultTemplateSid">Optional parameter: The default message [template](https://www.twilio.com/docs/verify/api/templates). Will be used for all SMS verifications unless explicitly overriden. SMS channel only..</param>
        /// <param name="whatsappMsgServiceSid">Optional parameter: The SID of the Messaging Service containing WhatsApp Sender(s) that Verify will use to send WhatsApp messages to your users..</param>
        /// <param name="whatsappFrom">Optional parameter: The number to use as the WhatsApp Sender that Verify will use to send WhatsApp messages to your users.This WhatsApp Sender must be associated with a Messaging Service SID..</param>
        /// <param name="passkeysRelyingPartyId">Optional parameter: The Relying Party ID for Passkeys. This is the domain of your application, e.g. `example.com`. It is used to identify your application when creating Passkeys..</param>
        /// <param name="passkeysRelyingPartyName">Optional parameter: The Relying Party Name for Passkeys. This is the name of your application, e.g. `Example App`. It is used to identify your application when creating Passkeys..</param>
        /// <param name="passkeysRelyingPartyOrigins">Optional parameter: The Relying Party Origins for Passkeys. This is the origin of your application, e.g. `login.example.com,www.example.com`. It is used to identify your application when creating Passkeys, it can have multiple origins split by `,`..</param>
        /// <param name="passkeysAuthenticatorAttachment">Optional parameter: The Authenticator Attachment for Passkeys. This is the type of authenticator that will be used to create Passkeys. It can be empty or it can have the values `platform`, `cross-platform` or `any`..</param>
        /// <param name="passkeysDiscoverableCredentials">Optional parameter: Indicates whether credentials must be discoverable by the authenticator. It can be empty or it can have the values `required`, `preferred` or `discouraged`..</param>
        /// <param name="passkeysUserVerification">Optional parameter: The User Verification for Passkeys. This is the type of user verification that will be used to create Passkeys. It can be empty or it can have the values `required`, `preferred` or `discouraged`..</param>
        /// <param name="verifyEventSubscriptionEnabled">Optional parameter: Whether to allow verifications from the service to reach the stream-events sinks if configured.</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.Service2 response from the API call.</returns>
        public async Task<ApiResponse<Models.Service2>> CreateServiceAsync(
                string friendlyName,
                int? codeLength = null,
                bool? lookupEnabled = null,
                bool? skipSmsToLandlines = null,
                bool? dtmfInputRequired = null,
                string ttsName = null,
                bool? psd2Enabled = null,
                bool? doNotShareWarningEnabled = null,
                bool? customCodeEnabled = null,
                bool? pushIncludeDate = null,
                string pushApnCredentialSid = null,
                string pushFcmCredentialSid = null,
                string totpIssuer = null,
                int? totpTimeStep = null,
                int? totpCodeLength = null,
                int? totpSkew = null,
                string defaultTemplateSid = null,
                string whatsappMsgServiceSid = null,
                string whatsappFrom = null,
                string passkeysRelyingPartyId = null,
                string passkeysRelyingPartyName = null,
                string passkeysRelyingPartyOrigins = null,
                string passkeysAuthenticatorAttachment = null,
                string passkeysDiscoverableCredentials = null,
                string passkeysUserVerification = null,
                bool? verifyEventSubscriptionEnabled = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.Service2>()
              .Server(Server.Default5)
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Post, "/v2/Services")
                  .WithAuth("accountSid_authToken")
                  .Parameters(parameters => parameters
                      .Header(header => header.Setup("Content-Type", "application/x-www-form-urlencoded"))
                      .Form(form => form.Setup("FriendlyName", friendlyName).Required())
                      .Form(form => form.Setup("CodeLength", codeLength))
                      .Form(form => form.Setup("LookupEnabled", lookupEnabled))
                      .Form(form => form.Setup("SkipSmsToLandlines", skipSmsToLandlines))
                      .Form(form => form.Setup("DtmfInputRequired", dtmfInputRequired))
                      .Form(form => form.Setup("TtsName", ttsName))
                      .Form(form => form.Setup("Psd2Enabled", psd2Enabled))
                      .Form(form => form.Setup("DoNotShareWarningEnabled", doNotShareWarningEnabled))
                      .Form(form => form.Setup("CustomCodeEnabled", customCodeEnabled))
                      .Form(form => form.Setup("Push.IncludeDate", pushIncludeDate))
                      .Form(form => form.Setup("Push.ApnCredentialSid", pushApnCredentialSid))
                      .Form(form => form.Setup("Push.FcmCredentialSid", pushFcmCredentialSid))
                      .Form(form => form.Setup("Totp.Issuer", totpIssuer))
                      .Form(form => form.Setup("Totp.TimeStep", totpTimeStep))
                      .Form(form => form.Setup("Totp.CodeLength", totpCodeLength))
                      .Form(form => form.Setup("Totp.Skew", totpSkew))
                      .Form(form => form.Setup("DefaultTemplateSid", defaultTemplateSid))
                      .Form(form => form.Setup("Whatsapp.MsgServiceSid", whatsappMsgServiceSid))
                      .Form(form => form.Setup("Whatsapp.From", whatsappFrom))
                      .Form(form => form.Setup("Passkeys.RelyingParty.Id", passkeysRelyingPartyId))
                      .Form(form => form.Setup("Passkeys.RelyingParty.Name", passkeysRelyingPartyName))
                      .Form(form => form.Setup("Passkeys.RelyingParty.Origins", passkeysRelyingPartyOrigins))
                      .Form(form => form.Setup("Passkeys.AuthenticatorAttachment", passkeysAuthenticatorAttachment))
                      .Form(form => form.Setup("Passkeys.DiscoverableCredentials", passkeysDiscoverableCredentials))
                      .Form(form => form.Setup("Passkeys.UserVerification", passkeysUserVerification))
                      .Form(form => form.Setup("VerifyEventSubscriptionEnabled", verifyEventSubscriptionEnabled))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);
    }
}